// Block Registry with original stylized blocks, properties, shapes, and textures
import { BlockDef, BlockType } from '../../types';

export const BLOCK_DEFS: Record<BlockType, BlockDef> = {
  [BlockType.AIR]: {
    id: BlockType.AIR,
    name: 'Air',
    category: 'natural',
    shape: 'full',
    hardness: 0,
    transparent: true,
    solid: false,
    color: [0, 0, 0],
    dropItem: '',
    soundType: 'grass',
  },
  [BlockType.GRASS]: {
    id: BlockType.GRASS,
    name: 'Verdant Turf',
    category: 'natural',
    shape: 'full',
    hardness: 0.6,
    requiredTool: 'shovel',
    solid: true,
    color: [0.32, 0.68, 0.28], // top
    topColor: [0.34, 0.72, 0.29],
    bottomColor: [0.42, 0.28, 0.17],
    sideColor: [0.38, 0.48, 0.22],
    dropItem: 'dirt',
    soundType: 'grass',
  },
  [BlockType.DIRT]: {
    id: BlockType.DIRT,
    name: 'Rich Soil',
    category: 'natural',
    shape: 'full',
    hardness: 0.5,
    requiredTool: 'shovel',
    solid: true,
    color: [0.44, 0.30, 0.18],
    dropItem: 'dirt',
    soundType: 'grass',
  },
  [BlockType.STONE]: {
    id: BlockType.STONE,
    name: 'Basalt Stone',
    category: 'stone',
    shape: 'full',
    hardness: 1.5,
    requiredTool: 'pickaxe',
    minToolTier: 0,
    solid: true,
    color: [0.52, 0.53, 0.56],
    dropItem: 'cobblestone',
    soundType: 'stone',
  },
  [BlockType.COBBLESTONE]: {
    id: BlockType.COBBLESTONE,
    name: 'Fractured Cobble',
    category: 'stone',
    shape: 'full',
    hardness: 2.0,
    requiredTool: 'pickaxe',
    solid: true,
    color: [0.45, 0.46, 0.48],
    dropItem: 'cobblestone',
    soundType: 'stone',
  },
  [BlockType.SAND]: {
    id: BlockType.SAND,
    name: 'Golden Sand',
    category: 'natural',
    shape: 'full',
    hardness: 0.5,
    requiredTool: 'shovel',
    solid: true,
    color: [0.86, 0.78, 0.52],
    dropItem: 'sand',
    soundType: 'sand',
  },
  [BlockType.GRAVEL]: {
    id: BlockType.GRAVEL,
    name: 'River Shingle',
    category: 'natural',
    shape: 'full',
    hardness: 0.6,
    requiredTool: 'shovel',
    solid: true,
    color: [0.55, 0.53, 0.50],
    dropItem: 'gravel',
    soundType: 'sand',
  },
  [BlockType.CLAY]: {
    id: BlockType.CLAY,
    name: 'Terracotta Clay',
    category: 'natural',
    shape: 'full',
    hardness: 0.7,
    requiredTool: 'shovel',
    solid: true,
    color: [0.65, 0.48, 0.40],
    dropItem: 'clay_ball',
    dropCount: [2, 4],
    soundType: 'sand',
  },
  [BlockType.OAK_LOG]: {
    id: BlockType.OAK_LOG,
    name: 'Ancient Oak Timber',
    category: 'wood',
    shape: 'full',
    hardness: 1.8,
    requiredTool: 'axe',
    solid: true,
    color: [0.38, 0.26, 0.16],
    topColor: [0.58, 0.46, 0.32],
    bottomColor: [0.58, 0.46, 0.32],
    sideColor: [0.38, 0.26, 0.16],
    dropItem: 'oak_log',
    soundType: 'wood',
  },
  [BlockType.OAK_LEAVES]: {
    id: BlockType.OAK_LEAVES,
    name: 'Canopy Foliage',
    category: 'foliage',
    shape: 'full',
    hardness: 0.2,
    transparent: true,
    solid: true,
    color: [0.24, 0.58, 0.22],
    dropItem: 'sapling_oak',
    soundType: 'grass',
  },
  [BlockType.PINE_LOG]: {
    id: BlockType.PINE_LOG,
    name: 'Boreal Pine Trunk',
    category: 'wood',
    shape: 'full',
    hardness: 1.8,
    requiredTool: 'axe',
    solid: true,
    color: [0.28, 0.20, 0.14],
    topColor: [0.48, 0.38, 0.26],
    bottomColor: [0.48, 0.38, 0.26],
    sideColor: [0.28, 0.20, 0.14],
    dropItem: 'pine_log',
    soundType: 'wood',
  },
  [BlockType.PINE_LEAVES]: {
    id: BlockType.PINE_LEAVES,
    name: 'Boreal Needles',
    category: 'foliage',
    shape: 'full',
    hardness: 0.2,
    transparent: true,
    solid: true,
    color: [0.18, 0.42, 0.30],
    dropItem: 'sapling_pine',
    soundType: 'grass',
  },
  [BlockType.CYAN_CRYSTAL_LOG]: {
    id: BlockType.CYAN_CRYSTAL_LOG,
    name: 'Aetherwood Stem',
    category: 'magic',
    shape: 'full',
    hardness: 2.2,
    requiredTool: 'axe',
    solid: true,
    lightEmission: 4,
    color: [0.25, 0.20, 0.38],
    topColor: [0.45, 0.35, 0.65],
    bottomColor: [0.45, 0.35, 0.65],
    sideColor: [0.28, 0.22, 0.42],
    dropItem: 'aether_log',
    soundType: 'wood',
  },
  [BlockType.CYAN_CRYSTAL_LEAVES]: {
    id: BlockType.CYAN_CRYSTAL_LEAVES,
    name: 'Luminescent Leaves',
    category: 'magic',
    shape: 'full',
    hardness: 0.3,
    transparent: true,
    solid: true,
    lightEmission: 8,
    color: [0.15, 0.75, 0.85],
    dropItem: 'aether_crystal',
    soundType: 'crystal',
  },
  [BlockType.WOOD_PLANKS]: {
    id: BlockType.WOOD_PLANKS,
    name: 'Timber Planks',
    category: 'building',
    shape: 'full',
    hardness: 1.5,
    requiredTool: 'axe',
    solid: true,
    color: [0.62, 0.46, 0.30],
    dropItem: 'wood_planks',
    soundType: 'wood',
  },
  [BlockType.WOOD_STAIRS]: {
    id: BlockType.WOOD_STAIRS,
    name: 'Timber Steps',
    category: 'building',
    shape: 'stairs',
    hardness: 1.5,
    requiredTool: 'axe',
    solid: true,
    transparent: true,
    color: [0.62, 0.46, 0.30],
    dropItem: 'wood_stairs',
    soundType: 'wood',
  },
  [BlockType.WOOD_SLAB]: {
    id: BlockType.WOOD_SLAB,
    name: 'Timber Half-Block',
    category: 'building',
    shape: 'slab',
    hardness: 1.2,
    requiredTool: 'axe',
    solid: true,
    transparent: true,
    color: [0.62, 0.46, 0.30],
    dropItem: 'wood_slab',
    soundType: 'wood',
  },
  [BlockType.STONE_BRICKS]: {
    id: BlockType.STONE_BRICKS,
    name: 'Carved Masonry',
    category: 'building',
    shape: 'full',
    hardness: 2.2,
    requiredTool: 'pickaxe',
    solid: true,
    color: [0.48, 0.50, 0.52],
    dropItem: 'stone_bricks',
    soundType: 'stone',
  },
  [BlockType.STONE_STAIRS]: {
    id: BlockType.STONE_STAIRS,
    name: 'Masonry Steps',
    category: 'building',
    shape: 'stairs',
    hardness: 2.2,
    requiredTool: 'pickaxe',
    solid: true,
    transparent: true,
    color: [0.48, 0.50, 0.52],
    dropItem: 'stone_stairs',
    soundType: 'stone',
  },
  [BlockType.STONE_SLAB]: {
    id: BlockType.STONE_SLAB,
    name: 'Masonry Slab',
    category: 'building',
    shape: 'slab',
    hardness: 1.8,
    requiredTool: 'pickaxe',
    solid: true,
    transparent: true,
    color: [0.48, 0.50, 0.52],
    dropItem: 'stone_slab',
    soundType: 'stone',
  },
  [BlockType.STONE_PILLAR]: {
    id: BlockType.STONE_PILLAR,
    name: 'Carved Colonnade',
    category: 'building',
    shape: 'pillar',
    hardness: 2.5,
    requiredTool: 'pickaxe',
    solid: true,
    color: [0.55, 0.56, 0.58],
    dropItem: 'stone_pillar',
    soundType: 'stone',
  },
  [BlockType.GLASS]: {
    id: BlockType.GLASS,
    name: 'Silica Glass',
    category: 'building',
    shape: 'full',
    hardness: 0.3,
    transparent: true,
    solid: true,
    color: [0.72, 0.88, 0.95],
    dropItem: 'glass',
    soundType: 'glass',
  },
  [BlockType.COPPER_ORE]: {
    id: BlockType.COPPER_ORE,
    name: 'Cuprite Mineral Vein',
    category: 'ore',
    shape: 'full',
    hardness: 2.2,
    requiredTool: 'pickaxe',
    minToolTier: 0,
    solid: true,
    color: [0.55, 0.45, 0.40],
    dropItem: 'raw_copper',
    soundType: 'stone',
  },
  [BlockType.IRON_ORE]: {
    id: BlockType.IRON_ORE,
    name: 'Hematite Iron Vein',
    category: 'ore',
    shape: 'full',
    hardness: 2.8,
    requiredTool: 'pickaxe',
    minToolTier: 1,
    solid: true,
    color: [0.60, 0.55, 0.50],
    dropItem: 'raw_iron',
    soundType: 'stone',
  },
  [BlockType.GOLD_ORE]: {
    id: BlockType.GOLD_ORE,
    name: 'Aurum Gold Vein',
    category: 'ore',
    shape: 'full',
    hardness: 3.0,
    requiredTool: 'pickaxe',
    minToolTier: 2,
    solid: true,
    color: [0.75, 0.65, 0.30],
    dropItem: 'raw_gold',
    soundType: 'stone',
  },
  [BlockType.MYTHRIL_ORE]: {
    id: BlockType.MYTHRIL_ORE,
    name: 'Mythril Ore Vein',
    category: 'ore',
    shape: 'full',
    hardness: 4.5,
    requiredTool: 'pickaxe',
    minToolTier: 2,
    solid: true,
    lightEmission: 5,
    color: [0.30, 0.60, 0.85],
    dropItem: 'raw_mythril',
    soundType: 'stone',
  },
  [BlockType.AETHER_CRYSTAL_ORE]: {
    id: BlockType.AETHER_CRYSTAL_ORE,
    name: 'Aether Geode Node',
    category: 'ore',
    shape: 'full',
    hardness: 5.0,
    requiredTool: 'pickaxe',
    minToolTier: 3,
    solid: true,
    lightEmission: 10,
    color: [0.70, 0.35, 0.90],
    dropItem: 'aether_crystal',
    dropCount: [1, 3],
    soundType: 'crystal',
  },
  [BlockType.COAL_ORE]: {
    id: BlockType.COAL_ORE,
    name: 'Carbon Bitumen Vein',
    category: 'ore',
    shape: 'full',
    hardness: 2.0,
    requiredTool: 'pickaxe',
    solid: true,
    color: [0.25, 0.25, 0.27],
    dropItem: 'coal',
    dropCount: [1, 2],
    soundType: 'stone',
  },
  [BlockType.WATER]: {
    id: BlockType.WATER,
    name: 'Shimmering Spring Water',
    category: 'liquid',
    shape: 'full',
    hardness: 100,
    transparent: true,
    solid: false,
    color: [0.15, 0.45, 0.85],
    dropItem: '',
    soundType: 'sand',
  },
  [BlockType.LAVA]: {
    id: BlockType.LAVA,
    name: 'Molten Magma Fluid',
    category: 'liquid',
    shape: 'full',
    hardness: 100,
    lightEmission: 15,
    transparent: false,
    solid: false,
    color: [0.95, 0.35, 0.05],
    dropItem: '',
    soundType: 'stone',
  },
  [BlockType.TORCH]: {
    id: BlockType.TORCH,
    name: 'Resin Beacon Torch',
    category: 'functional',
    shape: 'torch',
    hardness: 0.1,
    lightEmission: 14,
    transparent: true,
    solid: false,
    color: [0.98, 0.75, 0.30],
    dropItem: 'torch',
    soundType: 'wood',
  },
  [BlockType.LANTERN]: {
    id: BlockType.LANTERN,
    name: 'Gilded Lantern',
    category: 'functional',
    shape: 'torch',
    hardness: 0.5,
    lightEmission: 15,
    transparent: true,
    solid: false,
    color: [0.95, 0.82, 0.35],
    dropItem: 'lantern',
    soundType: 'metal',
  },
  [BlockType.GLOWSTONE_CRYSTAL]: {
    id: BlockType.GLOWSTONE_CRYSTAL,
    name: 'Prismatic Phosphor Block',
    category: 'magic',
    shape: 'full',
    hardness: 1.0,
    lightEmission: 15,
    solid: true,
    color: [0.90, 0.85, 0.40],
    dropItem: 'glow_dust',
    dropCount: [2, 4],
    soundType: 'glass',
  },
  [BlockType.TALL_GRASS]: {
    id: BlockType.TALL_GRASS,
    name: 'Wild Blade Flora',
    category: 'foliage',
    shape: 'cross',
    hardness: 0.1,
    transparent: true,
    solid: false,
    color: [0.35, 0.70, 0.28],
    dropItem: 'seeds',
    soundType: 'grass',
  },
  [BlockType.BLUE_FLOWER]: {
    id: BlockType.BLUE_FLOWER,
    name: 'Sapphire Bellflower',
    category: 'foliage',
    shape: 'cross',
    hardness: 0.1,
    transparent: true,
    solid: false,
    color: [0.20, 0.50, 0.95],
    dropItem: 'blue_flower',
    soundType: 'grass',
  },
  [BlockType.RED_FLOWER]: {
    id: BlockType.RED_FLOWER,
    name: 'Crimson Rosebloom',
    category: 'foliage',
    shape: 'cross',
    hardness: 0.1,
    transparent: true,
    solid: false,
    color: [0.92, 0.22, 0.28],
    dropItem: 'red_flower',
    soundType: 'grass',
  },
  [BlockType.SUN_ORCHID]: {
    id: BlockType.SUN_ORCHID,
    name: 'Golden Sun Orchid',
    category: 'foliage',
    shape: 'cross',
    hardness: 0.1,
    lightEmission: 3,
    transparent: true,
    solid: false,
    color: [0.98, 0.85, 0.15],
    dropItem: 'sun_orchid',
    soundType: 'grass',
  },
  [BlockType.LUMINESCENT_MUSHROOM]: {
    id: BlockType.LUMINESCENT_MUSHROOM,
    name: 'Biolume Spore Cap',
    category: 'magic',
    shape: 'cross',
    hardness: 0.1,
    lightEmission: 9,
    transparent: true,
    solid: false,
    color: [0.20, 0.85, 0.90],
    dropItem: 'lume_mushroom',
    soundType: 'grass',
  },
  [BlockType.SNOW]: {
    id: BlockType.SNOW,
    name: 'Permafrost Glaze',
    category: 'natural',
    shape: 'full',
    hardness: 0.4,
    requiredTool: 'shovel',
    solid: true,
    color: [0.92, 0.95, 0.98],
    dropItem: 'snowball',
    dropCount: [2, 4],
    soundType: 'snow',
  },
  [BlockType.ICE]: {
    id: BlockType.ICE,
    name: 'Glacial Clear Ice',
    category: 'natural',
    shape: 'full',
    hardness: 0.7,
    requiredTool: 'pickaxe',
    transparent: true,
    solid: true,
    color: [0.65, 0.82, 0.95],
    dropItem: 'ice_shard',
    soundType: 'glass',
  },
  [BlockType.OBSIDIAN]: {
    id: BlockType.OBSIDIAN,
    name: 'Vitric Obsidian',
    category: 'stone',
    shape: 'full',
    hardness: 10.0,
    requiredTool: 'pickaxe',
    minToolTier: 2,
    solid: true,
    color: [0.15, 0.12, 0.22],
    dropItem: 'obsidian',
    soundType: 'stone',
  },
  [BlockType.BASALT]: {
    id: BlockType.BASALT,
    name: 'Volcanic Scoria',
    category: 'stone',
    shape: 'full',
    hardness: 3.0,
    requiredTool: 'pickaxe',
    solid: true,
    color: [0.28, 0.28, 0.30],
    dropItem: 'basalt',
    soundType: 'stone',
  },
  [BlockType.MAGMA_ROCK]: {
    id: BlockType.MAGMA_ROCK,
    name: 'Igneous Emberstone',
    category: 'stone',
    shape: 'full',
    hardness: 3.0,
    requiredTool: 'pickaxe',
    lightEmission: 11,
    solid: true,
    color: [0.75, 0.30, 0.15],
    dropItem: 'magma_rock',
    soundType: 'stone',
  },
  [BlockType.ANCIENT_RUNE_STONE]: {
    id: BlockType.ANCIENT_RUNE_STONE,
    name: 'Glyph-Carved Relic Stone',
    category: 'magic',
    shape: 'full',
    hardness: 4.0,
    requiredTool: 'pickaxe',
    minToolTier: 1,
    lightEmission: 6,
    solid: true,
    color: [0.25, 0.45, 0.50],
    dropItem: 'ancient_glyph',
    soundType: 'stone',
  },
  [BlockType.CRAFTING_BENCH]: {
    id: BlockType.CRAFTING_BENCH,
    name: 'Artisan Workbench',
    category: 'functional',
    shape: 'full',
    hardness: 2.0,
    requiredTool: 'axe',
    solid: true,
    color: [0.55, 0.40, 0.25],
    topColor: [0.65, 0.48, 0.32],
    sideColor: [0.50, 0.35, 0.22],
    dropItem: 'crafting_bench',
    soundType: 'wood',
  },
  [BlockType.FURNACE]: {
    id: BlockType.FURNACE,
    name: 'Kiln Smelter',
    category: 'functional',
    shape: 'full',
    hardness: 3.0,
    requiredTool: 'pickaxe',
    solid: true,
    color: [0.42, 0.44, 0.46],
    dropItem: 'furnace',
    soundType: 'stone',
  },
  [BlockType.CHEST]: {
    id: BlockType.CHEST,
    name: 'Reinforced Storage Vault',
    category: 'functional',
    shape: 'full',
    hardness: 2.0,
    requiredTool: 'axe',
    solid: true,
    color: [0.52, 0.38, 0.20],
    dropItem: 'chest',
    soundType: 'wood',
  },
  [BlockType.DOOR_BOTTOM]: {
    id: BlockType.DOOR_BOTTOM,
    name: 'Paneled Timber Doorway',
    category: 'building',
    shape: 'door',
    hardness: 1.5,
    requiredTool: 'axe',
    solid: false,
    transparent: true,
    color: [0.55, 0.38, 0.22],
    dropItem: 'wooden_door',
    soundType: 'wood',
  },
  [BlockType.DOOR_TOP]: {
    id: BlockType.DOOR_TOP,
    name: 'Paneled Timber Doorway Top',
    category: 'building',
    shape: 'door',
    hardness: 1.5,
    requiredTool: 'axe',
    solid: false,
    transparent: true,
    color: [0.55, 0.38, 0.22],
    dropItem: 'wooden_door',
    soundType: 'wood',
  },
  [BlockType.FENCE_WOOD]: {
    id: BlockType.FENCE_WOOD,
    name: 'Timber Barrier Fence',
    category: 'building',
    shape: 'fence',
    hardness: 1.5,
    requiredTool: 'axe',
    solid: true,
    transparent: true,
    color: [0.58, 0.42, 0.26],
    dropItem: 'wood_fence',
    soundType: 'wood',
  },
  [BlockType.COPPER_BLOCK]: {
    id: BlockType.COPPER_BLOCK,
    name: 'Solid Bronze Alloy Block',
    category: 'building',
    shape: 'full',
    hardness: 4.0,
    requiredTool: 'pickaxe',
    minToolTier: 1,
    solid: true,
    color: [0.85, 0.52, 0.34],
    dropItem: 'copper_block',
    soundType: 'metal',
  },
  [BlockType.IRON_BLOCK]: {
    id: BlockType.IRON_BLOCK,
    name: 'Forged Ferrite Block',
    category: 'building',
    shape: 'full',
    hardness: 5.0,
    requiredTool: 'pickaxe',
    minToolTier: 1,
    solid: true,
    color: [0.82, 0.84, 0.86],
    dropItem: 'iron_block',
    soundType: 'metal',
  },
  [BlockType.GOLD_BLOCK]: {
    id: BlockType.GOLD_BLOCK,
    name: 'Ingot Aurum Block',
    category: 'building',
    shape: 'full',
    hardness: 3.5,
    requiredTool: 'pickaxe',
    minToolTier: 2,
    solid: true,
    color: [0.95, 0.82, 0.22],
    dropItem: 'gold_block',
    soundType: 'metal',
  },
  [BlockType.MYTHRIL_BLOCK]: {
    id: BlockType.MYTHRIL_BLOCK,
    name: 'Refined Mythril Monolith',
    category: 'building',
    shape: 'full',
    hardness: 6.0,
    requiredTool: 'pickaxe',
    minToolTier: 2,
    lightEmission: 7,
    solid: true,
    color: [0.35, 0.70, 0.95],
    dropItem: 'mythril_block',
    soundType: 'metal',
  },
  [BlockType.MOSS_STONE]: {
    id: BlockType.MOSS_STONE,
    name: 'Overgrown Mossy Masonry',
    category: 'building',
    shape: 'full',
    hardness: 2.2,
    requiredTool: 'pickaxe',
    solid: true,
    color: [0.40, 0.52, 0.42],
    dropItem: 'moss_stone',
    soundType: 'stone',
  },
  [BlockType.CORAL_BLOCK]: {
    id: BlockType.CORAL_BLOCK,
    name: 'Living Poly-Coral Colony',
    category: 'natural',
    shape: 'full',
    hardness: 1.2,
    requiredTool: 'pickaxe',
    lightEmission: 4,
    solid: true,
    color: [0.92, 0.45, 0.65],
    dropItem: 'coral_shard',
    soundType: 'stone',
  },
  [BlockType.BED_FOOT]: {
    id: BlockType.BED_FOOT,
    name: 'Explorer Rest Cot',
    category: 'functional',
    shape: 'slab',
    hardness: 1.0,
    requiredTool: 'axe',
    solid: true,
    transparent: true,
    color: [0.75, 0.25, 0.25],
    dropItem: 'explorer_bed',
    soundType: 'wood',
  },
  [BlockType.BED_HEAD]: {
    id: BlockType.BED_HEAD,
    name: 'Explorer Rest Cot Head',
    category: 'functional',
    shape: 'slab',
    hardness: 1.0,
    requiredTool: 'axe',
    solid: true,
    transparent: true,
    color: [0.85, 0.85, 0.90],
    dropItem: 'explorer_bed',
    soundType: 'wood',
  },
  [BlockType.BOOKSHELF]: {
    id: BlockType.BOOKSHELF,
    name: 'Ancient Tome Archive',
    category: 'building',
    shape: 'full',
    hardness: 1.5,
    requiredTool: 'axe',
    solid: true,
    color: [0.55, 0.38, 0.25],
    dropItem: 'ancient_tome',
    soundType: 'wood',
  },
  [BlockType.FARMLAND]: {
    id: BlockType.FARMLAND,
    name: 'Tilled Farmland Soil',
    category: 'farming',
    shape: 'slab',
    hardness: 0.5,
    requiredTool: 'shovel',
    solid: true,
    color: [0.36, 0.22, 0.12],
    topColor: [0.30, 0.18, 0.10],
    sideColor: [0.40, 0.26, 0.15],
    dropItem: 'dirt',
    soundType: 'grass',
  },
  [BlockType.CROP_WHEAT_0]: {
    id: BlockType.CROP_WHEAT_0,
    name: 'Golden Grain (Sprout)',
    category: 'foliage',
    shape: 'cross',
    hardness: 0.1,
    requiredTool: 'none',
    solid: false,
    transparent: true,
    color: [0.45, 0.75, 0.25],
    dropItem: 'seeds_wheat',
    soundType: 'grass',
  },
  [BlockType.CROP_WHEAT_1]: {
    id: BlockType.CROP_WHEAT_1,
    name: 'Golden Grain (Growing)',
    category: 'foliage',
    shape: 'cross',
    hardness: 0.1,
    requiredTool: 'none',
    solid: false,
    transparent: true,
    color: [0.65, 0.80, 0.20],
    dropItem: 'seeds_wheat',
    soundType: 'grass',
  },
  [BlockType.CROP_WHEAT_2]: {
    id: BlockType.CROP_WHEAT_2,
    name: 'Golden Grain (Ripening)',
    category: 'foliage',
    shape: 'cross',
    hardness: 0.1,
    requiredTool: 'none',
    solid: false,
    transparent: true,
    color: [0.85, 0.78, 0.22],
    dropItem: 'seeds_wheat',
    soundType: 'grass',
  },
  [BlockType.CROP_WHEAT_3]: {
    id: BlockType.CROP_WHEAT_3,
    name: 'Golden Grain (Mature Wheat)',
    category: 'foliage',
    shape: 'cross',
    hardness: 0.1,
    requiredTool: 'none',
    solid: false,
    transparent: true,
    color: [0.92, 0.80, 0.25],
    dropItem: 'crop_wheat',
    dropCount: [1, 2],
    soundType: 'grass',
  },
  [BlockType.CROP_CARROT]: {
    id: BlockType.CROP_CARROT,
    name: 'Wild Ember Carrot',
    category: 'foliage',
    shape: 'cross',
    hardness: 0.1,
    requiredTool: 'none',
    solid: false,
    transparent: true,
    color: [0.95, 0.52, 0.15],
    dropItem: 'wild_carrot',
    dropCount: [1, 3],
    soundType: 'grass',
  },
  [BlockType.CROP_HERB]: {
    id: BlockType.CROP_HERB,
    name: 'Astral Healing Herb',
    category: 'foliage',
    shape: 'cross',
    hardness: 0.1,
    requiredTool: 'none',
    solid: false,
    transparent: true,
    color: [0.25, 0.85, 0.65],
    dropItem: 'crop_herb',
    dropCount: [1, 2],
    soundType: 'grass',
  },
  [BlockType.ANVIL_SMITHING]: {
    id: BlockType.ANVIL_SMITHING,
    name: 'Forgemaster Smithing Anvil',
    category: 'functional',
    shape: 'full',
    hardness: 4.0,
    requiredTool: 'pickaxe',
    minToolTier: 1,
    solid: true,
    color: [0.28, 0.30, 0.35],
    dropItem: 'anvil_smithing',
    soundType: 'metal',
  },
};
