// Comprehensive Item Registry 2.0: Tier Progression, Tools, Armor Sets, Food Metabolism & Economy
import { BlockType, ItemDef } from '../../types';

export const ITEM_DEFS: Record<string, ItemDef> = {
  // ==========================================
  // 1. RAW MATERIALS, INGOTS & FUEL
  // ==========================================
  wood_planks: {
    id: 'wood_planks',
    name: 'Timber Planks',
    category: 'block',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#9e754c',
    description: 'Sturdy wooden building boards.',
    blockType: BlockType.WOOD_PLANKS,
    fuelBurnTime: 15,
    baseValue: 1,
  },
  oak_log: {
    id: 'oak_log',
    name: 'Ancient Oak Log',
    category: 'block',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#604229',
    description: 'Raw oak timber felled from primeval groves.',
    blockType: BlockType.OAK_LOG,
    fuelBurnTime: 30,
    baseValue: 4,
  },
  pine_log: {
    id: 'pine_log',
    name: 'Boreal Pine Log',
    category: 'block',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#473324',
    description: 'Dense fragrant pine wood.',
    blockType: BlockType.PINE_LOG,
    fuelBurnTime: 30,
    baseValue: 4,
  },
  aether_log: {
    id: 'aether_log',
    name: 'Aetherwood Stem',
    category: 'block',
    rarity: 'rare',
    maxStack: 64,
    iconColor: '#403361',
    description: 'Mystical crystal-infused wood infused with arcane ley energy.',
    blockType: BlockType.CYAN_CRYSTAL_LOG,
    fuelBurnTime: 60,
    baseValue: 12,
  },
  stick: {
    id: 'stick',
    name: 'Carved Wooden Rod',
    category: 'material',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#8c6747',
    description: 'Basic crafting handle used for tools and weapons.',
    fuelBurnTime: 5,
    baseValue: 1,
  },
  dirt: {
    id: 'dirt',
    name: 'Rich Soil',
    category: 'block',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#704d2e',
    description: 'Fertile earth suitable for farming with a hoe.',
    blockType: BlockType.DIRT,
    baseValue: 1,
  },
  sand: {
    id: 'sand',
    name: 'Golden Sand',
    category: 'block',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#dbc785',
    description: 'Fine quartz particles. Smelt in a kiln to make silica glass.',
    blockType: BlockType.SAND,
    baseValue: 1,
  },
  gravel: {
    id: 'gravel',
    name: 'River Shingle',
    category: 'block',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#8c8a85',
    description: 'Loose shingle that can yield flint shards.',
    blockType: BlockType.GRAVEL,
    baseValue: 1,
  },
  flint: {
    id: 'flint',
    name: 'Fractured Flint Shard',
    category: 'material',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#3d3e42',
    description: 'Sharp sedimentary stone used for arrows and crude tools.',
    baseValue: 2,
  },
  clay_ball: {
    id: 'clay_ball',
    name: 'Terracotta Clay Lump',
    category: 'material',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#a66e53',
    description: 'Soft sediment malleable for kiln firing.',
    baseValue: 2,
  },
  brick: {
    id: 'brick',
    name: 'Kiln Fired Brick',
    category: 'material',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#b34a36',
    description: 'Hardened masonry brick for fireproof structures.',
    baseValue: 3,
  },
  stone: {
    id: 'stone',
    name: 'Smooth Stone',
    category: 'block',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#808285',
    description: 'Smelted stone block suitable for stone masonry.',
    blockType: BlockType.STONE,
    baseValue: 1,
  },
  cobblestone: {
    id: 'cobblestone',
    name: 'Fractured Cobble',
    category: 'block',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#73757a',
    description: 'Rough stone blocks suitable for basic construction.',
    blockType: BlockType.COBBLESTONE,
    baseValue: 1,
  },
  stone_bricks: {
    id: 'stone_bricks',
    name: 'Carved Masonry Bricks',
    category: 'block',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#7a8085',
    description: 'Polished dressed stone blocks.',
    blockType: BlockType.STONE_BRICKS,
    baseValue: 2,
  },
  stone_pillar: {
    id: 'stone_pillar',
    name: 'Carved Colonnade Pillar',
    category: 'block',
    rarity: 'uncommon',
    maxStack: 64,
    iconColor: '#8c8f94',
    description: 'Architectural column for grand temples and vaulted ceilings.',
    blockType: BlockType.STONE_PILLAR,
    baseValue: 3,
  },
  glass: {
    id: 'glass',
    name: 'Silica Glass',
    category: 'block',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#b8e0f2',
    description: 'Transparent tempered window pane.',
    blockType: BlockType.GLASS,
    baseValue: 3,
  },
  coal: {
    id: 'coal',
    name: 'Carbon Bitumen Lump',
    category: 'material',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#2b2c30',
    description: 'High-energy smelting fuel providing 80s of burn time.',
    fuelBurnTime: 80,
    baseValue: 4,
  },
  charcoal: {
    id: 'charcoal',
    name: 'Pyrolyzed Charcoal',
    category: 'material',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#36373b',
    description: 'Smelted timber charcoal providing 70s of burn time.',
    fuelBurnTime: 70,
    baseValue: 3,
  },
  raw_copper: {
    id: 'raw_copper',
    name: 'Raw Cuprite Ore',
    category: 'material',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#8c5947',
    description: 'Unrefined copper mineral. Smelt in a kiln to produce ingots.',
    baseValue: 4,
  },
  copper_ingot: {
    id: 'copper_ingot',
    name: 'Forged Bronze Ingot',
    category: 'material',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#d98457',
    description: 'Ductile metallic bar used for Tier 1 tools and armor.',
    baseValue: 8,
  },
  raw_iron: {
    id: 'raw_iron',
    name: 'Raw Hematite Ore',
    category: 'material',
    rarity: 'uncommon',
    maxStack: 64,
    iconColor: '#998c80',
    description: 'Dense magnetic iron chunk.',
    baseValue: 8,
  },
  iron_ingot: {
    id: 'iron_ingot',
    name: 'Ferrite Steel Ingot',
    category: 'material',
    rarity: 'uncommon',
    maxStack: 64,
    iconColor: '#d1d6dc',
    description: 'Hardened structural metal for Tier 2 gear.',
    baseValue: 16,
  },
  raw_gold: {
    id: 'raw_gold',
    name: 'Raw Aurum Ore',
    category: 'material',
    rarity: 'rare',
    maxStack: 64,
    iconColor: '#c2a54d',
    description: 'Precious metallic cluster found in deep chasms.',
    baseValue: 18,
  },
  gold_ingot: {
    id: 'gold_ingot',
    name: 'Refined Aurum Bar',
    category: 'material',
    rarity: 'rare',
    maxStack: 64,
    iconColor: '#f2d138',
    description: 'Conductive precious ingot for enchantments, crowns, and relics.',
    baseValue: 35,
  },
  raw_mythril: {
    id: 'raw_mythril',
    name: 'Raw Mythril Ore',
    category: 'material',
    rarity: 'epic',
    maxStack: 64,
    iconColor: '#4d99d9',
    description: 'Ultra-light celestial metallic ore found in deep abyss chasms.',
    baseValue: 40,
  },
  mythril_ingot: {
    id: 'mythril_ingot',
    name: 'Astral Mythril Ingot',
    category: 'material',
    rarity: 'epic',
    maxStack: 64,
    iconColor: '#59b3f2',
    description: 'Pristine Tier 3 metal with supreme durability and razor sharpness.',
    baseValue: 80,
  },
  aether_crystal: {
    id: 'aether_crystal',
    name: 'Aether Prism Shard',
    category: 'material',
    rarity: 'legendary',
    maxStack: 64,
    iconColor: '#b359e6',
    description: 'Pure concentrated magical energy resonating from cosmic rifts.',
    baseValue: 150,
  },
  ancient_alloy: {
    id: 'ancient_alloy',
    name: 'Titanforged Astral Core',
    category: 'material',
    rarity: 'ancient',
    maxStack: 16,
    iconColor: '#2ae8c8',
    description: 'Relic metallurgical wonder from the lost builders of the realm.',
    baseValue: 300,
  },
  ancient_tome: {
    id: 'ancient_tome',
    name: 'Archivist Codex',
    category: 'material',
    rarity: 'rare',
    maxStack: 16,
    iconColor: '#5c4530',
    description: 'Bound parchment containing lost architectural formulae.',
    baseValue: 25,
  },
  leather_pelt: {
    id: 'leather_pelt',
    name: 'Tanned Beast Hide',
    category: 'material',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#8a5229',
    description: 'Supple warm hide for leather armor and backpacks.',
    baseValue: 5,
  },
  monster_bone: {
    id: 'monster_bone',
    name: 'Grave Fiend Bone',
    category: 'material',
    rarity: 'uncommon',
    maxStack: 64,
    iconColor: '#e0dedb',
    description: 'Hardened ossified material. Can be crushed into bone meal fertilizer.',
    baseValue: 6,
  },
  feather: {
    id: 'feather',
    name: 'Highland Gryphon Plume',
    category: 'material',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#d6d2c4',
    description: 'Aerodynamic fletching for projectile craft.',
    baseValue: 2,
  },

  // ==========================================
  // 2. TOOLS & HARVESTING GEAR
  // ==========================================
  // Pickaxes
  wooden_pickaxe: {
    id: 'wooden_pickaxe',
    name: 'Timber Pickaxe',
    category: 'tool',
    rarity: 'common',
    maxStack: 1,
    iconColor: '#a67b51',
    description: 'Basic mining tool for excavating soft stone and copper ore.',
    toolType: 'pickaxe',
    tier: 0,
    miningEfficiency: 1.8,
    attackDamage: 3,
    attackSpeed: 1.2,
    durability: 60,
    repairMaterial: 'wood_planks',
    baseValue: 5,
  },
  stone_pickaxe: {
    id: 'stone_pickaxe',
    name: 'Cobble Pickaxe',
    category: 'tool',
    rarity: 'common',
    maxStack: 1,
    iconColor: '#7a7c80',
    description: 'Flint-tipped stone pickaxe. Good early workhorse.',
    toolType: 'pickaxe',
    tier: 0,
    miningEfficiency: 2.6,
    attackDamage: 4,
    attackSpeed: 1.2,
    durability: 120,
    repairMaterial: 'cobblestone',
    baseValue: 8,
  },
  copper_pickaxe: {
    id: 'copper_pickaxe',
    name: 'Bronze Pickaxe',
    category: 'tool',
    rarity: 'common',
    maxStack: 1,
    iconColor: '#d98457',
    description: 'Sturdy bronze pick capable of mining iron ore.',
    toolType: 'pickaxe',
    tier: 1,
    miningEfficiency: 4.2,
    attackDamage: 5,
    attackSpeed: 1.2,
    durability: 200,
    repairMaterial: 'copper_ingot',
    baseValue: 20,
  },
  iron_pickaxe: {
    id: 'iron_pickaxe',
    name: 'Ferrite Pickaxe',
    category: 'tool',
    rarity: 'uncommon',
    maxStack: 1,
    iconColor: '#d1d6dc',
    description: 'Heavy duty steel pick for gold and deep subterranean stone.',
    toolType: 'pickaxe',
    tier: 2,
    miningEfficiency: 6.8,
    attackDamage: 7,
    attackSpeed: 1.2,
    durability: 450,
    repairMaterial: 'iron_ingot',
    baseValue: 45,
  },
  mythril_pickaxe: {
    id: 'mythril_pickaxe',
    name: 'Astral Mythril Pickaxe',
    category: 'tool',
    rarity: 'epic',
    maxStack: 1,
    iconColor: '#59b3f2',
    description: 'Weightless crystalline pick that shreds obsidian and geodes.',
    toolType: 'pickaxe',
    tier: 3,
    miningEfficiency: 11.0,
    attackDamage: 10,
    attackSpeed: 1.3,
    durability: 1100,
    repairMaterial: 'mythril_ingot',
    baseValue: 180,
  },
  aether_pickaxe: {
    id: 'aether_pickaxe',
    name: 'Titanforged Void Pickaxe',
    category: 'tool',
    rarity: 'legendary',
    maxStack: 1,
    iconColor: '#a855f7',
    description: 'Cosmic tool that fractures bedrock and instant-excavates veins.',
    toolType: 'pickaxe',
    tier: 4,
    miningEfficiency: 16.0,
    attackDamage: 14,
    attackSpeed: 1.4,
    durability: 2500,
    repairMaterial: 'aether_crystal',
    baseValue: 400,
  },

  // Axes
  wooden_axe: {
    id: 'wooden_axe',
    name: 'Timber Hatchet',
    category: 'tool',
    rarity: 'common',
    maxStack: 1,
    iconColor: '#a67b51',
    description: 'Harvests timber and chops logs quickly.',
    toolType: 'axe',
    tier: 0,
    miningEfficiency: 2.0,
    attackDamage: 5,
    attackSpeed: 1.0,
    durability: 60,
    repairMaterial: 'wood_planks',
    baseValue: 5,
  },
  copper_axe: {
    id: 'copper_axe',
    name: 'Bronze Felling Axe',
    category: 'tool',
    rarity: 'common',
    maxStack: 1,
    iconColor: '#d98457',
    description: 'Sharp bronze axe for rapid lumberjack forestry.',
    toolType: 'axe',
    tier: 1,
    miningEfficiency: 4.2,
    attackDamage: 8,
    attackSpeed: 1.0,
    durability: 200,
    repairMaterial: 'copper_ingot',
    baseValue: 20,
  },
  iron_axe: {
    id: 'iron_axe',
    name: 'Forged Battle-Axe',
    category: 'tool',
    rarity: 'uncommon',
    maxStack: 1,
    iconColor: '#d1d6dc',
    description: 'Powerful lumber tool and heavy cleaving weapon.',
    toolType: 'axe',
    tier: 2,
    miningEfficiency: 7.0,
    attackDamage: 14,
    attackSpeed: 0.9,
    durability: 450,
    repairMaterial: 'iron_ingot',
    baseValue: 45,
  },
  mythril_axe: {
    id: 'mythril_axe',
    name: 'Astral War-Axe',
    category: 'tool',
    rarity: 'epic',
    maxStack: 1,
    iconColor: '#59b3f2',
    description: 'Celestial axe with unmatched cutting precision.',
    toolType: 'axe',
    tier: 3,
    miningEfficiency: 11.5,
    attackDamage: 20,
    attackSpeed: 1.0,
    durability: 1100,
    repairMaterial: 'mythril_ingot',
    baseValue: 180,
  },

  // Shovels
  wooden_shovel: {
    id: 'wooden_shovel',
    name: 'Timber Spade',
    category: 'tool',
    rarity: 'common',
    maxStack: 1,
    iconColor: '#a67b51',
    description: 'Excavates dirt, sand, and gravel rapidly.',
    toolType: 'shovel',
    tier: 0,
    miningEfficiency: 2.5,
    attackDamage: 2,
    durability: 60,
    repairMaterial: 'wood_planks',
    baseValue: 3,
  },
  copper_shovel: {
    id: 'copper_shovel',
    name: 'Bronze Excavator',
    category: 'tool',
    rarity: 'common',
    maxStack: 1,
    iconColor: '#d98457',
    description: 'Reinforced bronze shovel for terrain landscaping.',
    toolType: 'shovel',
    tier: 1,
    miningEfficiency: 5.0,
    attackDamage: 4,
    durability: 200,
    repairMaterial: 'copper_ingot',
    baseValue: 15,
  },
  iron_shovel: {
    id: 'iron_shovel',
    name: 'Steel Trench Spade',
    category: 'tool',
    rarity: 'uncommon',
    maxStack: 1,
    iconColor: '#d1d6dc',
    description: 'Reinforced spade for high-speed terraforming.',
    toolType: 'shovel',
    tier: 2,
    miningEfficiency: 8.0,
    attackDamage: 6,
    durability: 450,
    repairMaterial: 'iron_ingot',
    baseValue: 35,
  },

  // Hoes & Farming Tools
  wooden_hoe: {
    id: 'wooden_hoe',
    name: 'Timber Cultivator',
    category: 'tool',
    rarity: 'common',
    maxStack: 1,
    iconColor: '#a67b51',
    description: 'Tills grass and soil into fertile farmland for crops.',
    toolType: 'hoe',
    tier: 0,
    durability: 60,
    repairMaterial: 'wood_planks',
    baseValue: 4,
  },
  iron_hoe: {
    id: 'iron_hoe',
    name: 'Ferrite Agricultural Hoe',
    category: 'tool',
    rarity: 'uncommon',
    maxStack: 1,
    iconColor: '#d1d6dc',
    description: 'Durable steel farming tool for extensive crop fields.',
    toolType: 'hoe',
    tier: 2,
    durability: 400,
    repairMaterial: 'iron_ingot',
    baseValue: 30,
  },

  // ==========================================
  // 3. WEAPONS & COMBAT
  // ==========================================
  wooden_sword: {
    id: 'wooden_sword',
    name: 'Hardwood Practice Blade',
    category: 'weapon',
    rarity: 'common',
    maxStack: 1,
    iconColor: '#8a623a',
    description: 'Light wooden sword for fending off small nocturnal beasts.',
    attackDamage: 6,
    attackSpeed: 1.6,
    durability: 55,
    repairMaterial: 'wood_planks',
    baseValue: 4,
  },
  copper_blade: {
    id: 'copper_blade',
    name: 'Bronze Gladius',
    category: 'weapon',
    rarity: 'common',
    maxStack: 1,
    iconColor: '#d98457',
    description: 'Swift balanced blade for melee encounters.',
    attackDamage: 12,
    attackSpeed: 1.6,
    durability: 180,
    repairMaterial: 'copper_ingot',
    baseValue: 18,
  },
  iron_blade: {
    id: 'iron_blade',
    name: 'Ferrite Longsword',
    category: 'weapon',
    rarity: 'uncommon',
    maxStack: 1,
    iconColor: '#d1d6dc',
    description: 'Tempered steel blade dealing devastating sweeping strikes.',
    attackDamage: 20,
    attackSpeed: 1.5,
    durability: 380,
    repairMaterial: 'iron_ingot',
    baseValue: 42,
  },
  mythril_saber: {
    id: 'mythril_saber',
    name: 'Astral Mythril Saber',
    category: 'weapon',
    rarity: 'epic',
    maxStack: 1,
    iconColor: '#59b3f2',
    description: 'Bladesmith masterpiece humming with celestial radiance.',
    attackDamage: 32,
    attackSpeed: 1.8,
    durability: 950,
    repairMaterial: 'mythril_ingot',
    baseValue: 190,
  },
  aether_staff: {
    id: 'aether_staff',
    name: 'Prismatic Archon Staff',
    category: 'weapon',
    rarity: 'legendary',
    maxStack: 1,
    iconColor: '#b359e6',
    description: 'Harnesses raw arcane vortex bolts against distant enemies.',
    attackDamage: 45,
    attackSpeed: 1.2,
    durability: 1400,
    repairMaterial: 'aether_crystal',
    baseValue: 450,
  },
  hunting_bow: {
    id: 'hunting_bow',
    name: 'Recurve Hunting Bow',
    category: 'weapon',
    rarity: 'common',
    maxStack: 1,
    iconColor: '#785334',
    description: 'Flexible composite bow for long-range precision shots.',
    attackDamage: 16,
    attackSpeed: 1.0,
    durability: 150,
    repairMaterial: 'wood_planks',
    baseValue: 16,
  },
  wooden_arrow: {
    id: 'wooden_arrow',
    name: 'Flint-Headed Arrow',
    category: 'material',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#9c9287',
    description: 'Standard ammunition fired from bows.',
    baseValue: 1,
  },

  // ==========================================
  // 4. ARMOR SETS (Defense & Survival Insulation)
  // ==========================================
  // Leather Set (Tier 0 / Thermal Warmth)
  leather_cap: {
    id: 'leather_cap',
    name: 'Trapper Fur Hood',
    category: 'armor',
    armorSlot: 'head',
    rarity: 'common',
    maxStack: 1,
    iconColor: '#8a5229',
    description: 'Warm fur-lined hood. Offers basic protection and cold insulation.',
    armorValue: 4,
    durability: 80,
    repairMaterial: 'leather_pelt',
    baseValue: 8,
  },
  leather_tunic: {
    id: 'leather_tunic',
    name: 'Trapper Leather Vest',
    category: 'armor',
    armorSlot: 'chest',
    rarity: 'common',
    maxStack: 1,
    iconColor: '#8a5229',
    description: 'Supple chest vest providing cold insulation.',
    armorValue: 8,
    durability: 120,
    repairMaterial: 'leather_pelt',
    baseValue: 14,
  },
  leather_pants: {
    id: 'leather_pants',
    name: 'Trapper Hide Breeches',
    category: 'armor',
    armorSlot: 'legs',
    rarity: 'common',
    maxStack: 1,
    iconColor: '#8a5229',
    description: 'Flexible leather pants for wilderness exploration.',
    armorValue: 6,
    durability: 100,
    repairMaterial: 'leather_pelt',
    baseValue: 11,
  },
  leather_boots: {
    id: 'leather_boots',
    name: 'Trapper Moccasins',
    category: 'armor',
    armorSlot: 'feet',
    rarity: 'common',
    maxStack: 1,
    iconColor: '#8a5229',
    description: 'Light soft-sole boots that reduce fall damage slightly.',
    armorValue: 3,
    durability: 75,
    repairMaterial: 'leather_pelt',
    baseValue: 7,
  },

  // Copper / Bronze Set (Tier 1)
  copper_helmet: {
    id: 'copper_helmet',
    name: 'Bronze Hoplite Sallet',
    category: 'armor',
    armorSlot: 'head',
    rarity: 'common',
    maxStack: 1,
    iconColor: '#d98457',
    description: 'Shining bronze helmet with protective cheekguards.',
    armorValue: 8,
    durability: 140,
    repairMaterial: 'copper_ingot',
    baseValue: 18,
  },
  copper_chestplate: {
    id: 'copper_chestplate',
    name: 'Bronze Hoplite Cuirass',
    category: 'armor',
    armorSlot: 'chest',
    rarity: 'common',
    maxStack: 1,
    iconColor: '#d98457',
    description: 'Hand-hammered bronze breastplate.',
    armorValue: 16,
    durability: 200,
    repairMaterial: 'copper_ingot',
    baseValue: 32,
  },
  copper_greaves: {
    id: 'copper_greaves',
    name: 'Bronze Hoplite Greaves',
    category: 'armor',
    armorSlot: 'legs',
    rarity: 'common',
    maxStack: 1,
    iconColor: '#d98457',
    description: 'Articulated bronze leg protection.',
    armorValue: 12,
    durability: 180,
    repairMaterial: 'copper_ingot',
    baseValue: 24,
  },
  copper_boots: {
    id: 'copper_boots',
    name: 'Bronze Hoplite Sabatons',
    category: 'armor',
    armorSlot: 'feet',
    rarity: 'common',
    maxStack: 1,
    iconColor: '#d98457',
    description: 'Reinforced bronze boots.',
    armorValue: 6,
    durability: 120,
    repairMaterial: 'copper_ingot',
    baseValue: 15,
  },

  // Iron / Ferrite Set (Tier 2)
  iron_helmet: {
    id: 'iron_helmet',
    name: 'Ferrite Greathelm',
    category: 'armor',
    armorSlot: 'head',
    rarity: 'uncommon',
    maxStack: 1,
    iconColor: '#d1d6dc',
    description: 'Steel cranial guard with reinforced visor.',
    armorValue: 14,
    durability: 220,
    repairMaterial: 'iron_ingot',
    baseValue: 35,
  },
  iron_chestplate: {
    id: 'iron_chestplate',
    name: 'Ferrite Cuirass',
    category: 'armor',
    armorSlot: 'chest',
    rarity: 'uncommon',
    maxStack: 1,
    iconColor: '#d1d6dc',
    description: 'Solid heavy breastplate protecting vital organs.',
    armorValue: 28,
    durability: 350,
    repairMaterial: 'iron_ingot',
    baseValue: 65,
  },
  iron_greaves: {
    id: 'iron_greaves',
    name: 'Ferrite Greaves',
    category: 'armor',
    armorSlot: 'legs',
    rarity: 'uncommon',
    maxStack: 1,
    iconColor: '#d1d6dc',
    description: 'Articulated plate armor for the legs.',
    armorValue: 20,
    durability: 300,
    repairMaterial: 'iron_ingot',
    baseValue: 50,
  },
  iron_boots: {
    id: 'iron_boots',
    name: 'Ferrite Sabatons',
    category: 'armor',
    armorSlot: 'feet',
    rarity: 'uncommon',
    maxStack: 1,
    iconColor: '#d1d6dc',
    description: 'Heavy steel footwear giving steady footing.',
    armorValue: 12,
    durability: 200,
    repairMaterial: 'iron_ingot',
    baseValue: 30,
  },

  // Mythril Astral Set (Tier 3)
  mythril_helmet: {
    id: 'mythril_helmet',
    name: 'Astral Mythril Diadem',
    category: 'armor',
    armorSlot: 'head',
    rarity: 'epic',
    maxStack: 1,
    iconColor: '#59b3f2',
    description: 'Crown forged of lightweight celestial alloy.',
    armorValue: 22,
    durability: 600,
    repairMaterial: 'mythril_ingot',
    baseValue: 140,
  },
  mythril_chestplate: {
    id: 'mythril_chestplate',
    name: 'Astral Mythril Plate',
    category: 'armor',
    armorSlot: 'chest',
    rarity: 'epic',
    maxStack: 1,
    iconColor: '#59b3f2',
    description: 'Superb chestplate repelling powerful blows effortlessly.',
    armorValue: 42,
    durability: 900,
    repairMaterial: 'mythril_ingot',
    baseValue: 280,
  },
  mythril_greaves: {
    id: 'mythril_greaves',
    name: 'Astral Mythril Legguards',
    category: 'armor',
    armorSlot: 'legs',
    rarity: 'epic',
    maxStack: 1,
    iconColor: '#59b3f2',
    description: 'Featherlight combat greaves.',
    armorValue: 30,
    durability: 750,
    repairMaterial: 'mythril_ingot',
    baseValue: 210,
  },
  mythril_boots: {
    id: 'mythril_boots',
    name: 'Astral Mythril Greaves',
    category: 'armor',
    armorSlot: 'feet',
    rarity: 'epic',
    maxStack: 1,
    iconColor: '#59b3f2',
    description: 'Empowers sprint speed and reduces fall damage.',
    armorValue: 18,
    durability: 550,
    repairMaterial: 'mythril_ingot',
    baseValue: 130,
  },

  // Relic Accessories
  ring_of_vitality: {
    id: 'ring_of_vitality',
    name: 'Amulet of the Sun Ward',
    category: 'accessory',
    armorSlot: 'accessory',
    rarity: 'rare',
    maxStack: 1,
    iconColor: '#f59e0b',
    description: 'Ancient pendant that grants +25 Max Health and thermal resistance.',
    armorValue: 8,
    givesEffect: {
      id: 'regeneration',
      duration: 300,
      magnitude: 1,
    },
    baseValue: 150,
  },

  eye_of_aether: {
    id: 'eye_of_aether',
    name: 'Eye of the Aetherborn',
    category: 'accessory',
    armorSlot: 'accessory',
    rarity: 'epic',
    maxStack: 1,
    iconColor: '#38bdf8',
    description: 'Relic: Pulsing orb that grants continuous soft regeneration and illumination.',
    armorValue: 10,
    givesEffect: {
      id: 'regeneration',
      duration: 9999,
      magnitude: 1,
    },
    baseValue: 400,
  },
  chrono_core: {
    id: 'chrono_core',
    name: 'Perpetual Chrono Core',
    category: 'accessory',
    armorSlot: 'accessory',
    rarity: 'epic',
    maxStack: 1,
    iconColor: '#fbbf24',
    description: 'Relic: Kinetic heart. Substantially increases energy and movement speed.',
    armorValue: 10,
    baseValue: 500,
  },
  solaris_aegis: {
    id: 'solaris_aegis',
    name: 'Solaris Aegis Medallion',
    category: 'accessory',
    armorSlot: 'accessory',
    rarity: 'legendary',
    maxStack: 1,
    iconColor: '#f97316',
    description: 'Relic: Medallion forged from magma crystals, offering immense defense.',
    armorValue: 35,
    baseValue: 800,
  },
  tidal_pearl: {
    id: 'tidal_pearl',
    name: 'Pearl of the Abyssal Siren',
    category: 'accessory',
    armorSlot: 'accessory',
    rarity: 'epic',
    maxStack: 1,
    iconColor: '#2dd4bf',
    description: 'Relic: Siren relic that increases underwater oxygen capacity and speed.',
    armorValue: 12,
    baseValue: 450,
  },
  void_walker_ring: {
    id: 'void_walker_ring',
    name: 'Ring of the Void Sovereign',
    category: 'accessory',
    armorSlot: 'accessory',
    rarity: 'ancient',
    maxStack: 1,
    iconColor: '#c084fc',
    description: 'Relic: Sovereign band granting dark energy immunity and critical defense.',
    armorValue: 45,
    baseValue: 1200,
  },
  precursor_matrix: {
    id: 'precursor_matrix',
    name: 'Precursor Knowledge Matrix',
    category: 'accessory',
    armorSlot: 'accessory',
    rarity: 'ancient',
    maxStack: 1,
    iconColor: '#ec4899',
    description: 'Relic: floating memory matrix unlocking masterwork blueprints and shields.',
    armorValue: 20,
    baseValue: 1500,
  },

  // ==========================================
  // 5. FOOD, FARMING SEEDS & CONSUMABLES
  // ==========================================
  seeds_wheat: {
    id: 'seeds_wheat',
    name: 'Golden Grain Seeds',
    category: 'seed',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#c4b574',
    description: 'Plant on tilled farmland soil to grow wheat.',
    baseValue: 1,
  },
  crop_wheat: {
    id: 'crop_wheat',
    name: 'Harvested Golden Grain',
    category: 'material',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#e0c058',
    description: 'Ripe wheat sheaves ready to be ground into flour and baked into bread.',
    baseValue: 2,
  },
  wild_carrot: {
    id: 'wild_carrot',
    name: 'Wild Ember Carrot',
    category: 'food',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#f97316',
    description: 'Crunchy vitamin-rich root. Restores 22 Hunger and 15 Saturation.',
    foodValue: 22,
    saturationValue: 15,
    staminaRestore: 12,
    consumeTime: 1.5,
    baseValue: 3,
  },
  crop_potato: {
    id: 'crop_potato',
    name: 'Highland Russet Potato',
    category: 'food',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#a88151',
    description: 'Dense starchy tuber. Smelt in kiln for delicious baked potato.',
    foodValue: 18,
    saturationValue: 10,
    staminaRestore: 10,
    consumeTime: 1.5,
    baseValue: 2,
  },
  baked_potato: {
    id: 'baked_potato',
    name: 'Kiln-Roasted Potato',
    category: 'food',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#c49a62',
    description: 'Warm roasted potato providing comfort in cold biomes. Restores 38 Hunger.',
    foodValue: 38,
    saturationValue: 28,
    staminaRestore: 25,
    healValue: 5,
    consumeTime: 1.4,
    baseValue: 5,
  },
  crop_herb: {
    id: 'crop_herb',
    name: 'Astral Healing Herb',
    category: 'material',
    rarity: 'uncommon',
    maxStack: 64,
    iconColor: '#10b981',
    description: 'Medicinal leaf utilized in vitality elixirs and soothing teas.',
    baseValue: 5,
  },
  berries: {
    id: 'berries',
    name: 'Crimson Sun Berries',
    category: 'food',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#e63946',
    description: 'Juicy wild berries harvested from meadow bushes. Restores 16 Hunger.',
    foodValue: 16,
    saturationValue: 8,
    staminaRestore: 12,
    consumeTime: 1.2,
    baseValue: 2,
  },
  bread: {
    id: 'bread',
    name: 'Hearth Loaf',
    category: 'food',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#d4a373',
    description: 'Baked wheat loaf. Restores 40 Hunger and 35 Saturation.',
    foodValue: 40,
    saturationValue: 35,
    staminaRestore: 30,
    healValue: 8,
    consumeTime: 1.6,
    baseValue: 6,
  },
  raw_meat: {
    id: 'raw_meat',
    name: 'Raw Primeval Game Meat',
    category: 'food',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#8a2b2b',
    description: 'Uncooked meat cut from wild game. Best cooked to avoid parasite weakness.',
    foodValue: 18,
    saturationValue: 8,
    staminaRestore: 10,
    consumeTime: 1.8,
    baseValue: 4,
  },
  cooked_meat: {
    id: 'cooked_meat',
    name: 'Roasted Stag Tenderloin',
    category: 'food',
    rarity: 'uncommon',
    maxStack: 64,
    iconColor: '#9c412b',
    description: 'Hearty roasted cut providing sustained vigor. Restores 60 Hunger and 50 Saturation.',
    foodValue: 60,
    saturationValue: 50,
    staminaRestore: 45,
    healValue: 18,
    consumeTime: 1.8,
    givesEffect: {
      id: 'well_fed',
      duration: 60,
      magnitude: 1,
    },
    baseValue: 12,
  },
  raw_fish: {
    id: 'raw_fish',
    name: 'Raw Silver Tide Fish',
    category: 'food',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#7a9fb8',
    description: 'Fresh river catch with shimmering scales.',
    foodValue: 15,
    saturationValue: 6,
    staminaRestore: 10,
    consumeTime: 1.5,
    baseValue: 3,
  },
  cooked_fish: {
    id: 'cooked_fish',
    name: 'Seared Silver Fillet',
    category: 'food',
    rarity: 'uncommon',
    maxStack: 64,
    iconColor: '#d68e58',
    description: 'Crisp seared river fish providing rich omega vitality.',
    foodValue: 48,
    saturationValue: 38,
    staminaRestore: 35,
    healValue: 12,
    consumeTime: 1.5,
    baseValue: 9,
  },
  hearty_stew: {
    id: 'hearty_stew',
    name: 'Nomad Forest Stew',
    category: 'food',
    rarity: 'rare',
    maxStack: 16,
    iconColor: '#854d0e',
    description: 'Slow-simmered vegetable and meat stew. Restores 85 Hunger, 70 Saturation, and 30 Health.',
    foodValue: 85,
    saturationValue: 70,
    staminaRestore: 60,
    healValue: 30,
    consumeTime: 2.2,
    givesEffect: {
      id: 'well_fed',
      duration: 120,
      magnitude: 2,
    },
    baseValue: 25,
  },
  golden_fruit: {
    id: 'golden_fruit',
    name: 'Auric Ambrosia Apple',
    category: 'food',
    rarity: 'legendary',
    maxStack: 16,
    iconColor: '#facc15',
    description: 'Legendary orchard harvest granting instant full recovery, regeneration, and damage boost.',
    foodValue: 100,
    saturationValue: 100,
    staminaRestore: 100,
    healValue: 75,
    consumeTime: 1.5,
    givesEffect: {
      id: 'regeneration',
      duration: 30,
      magnitude: 3,
    },
    baseValue: 200,
  },
  healing_potion: {
    id: 'healing_potion',
    name: 'Vitality Draught',
    category: 'consumable',
    rarity: 'rare',
    maxStack: 16,
    iconColor: '#10b981',
    description: 'Alchemical tincture that instantly restores 50 Health and cures poison.',
    healValue: 50,
    staminaRestore: 25,
    consumeTime: 1.2,
    givesEffect: {
      id: 'regeneration',
      duration: 15,
      magnitude: 2,
    },
    baseValue: 35,
  },
  swiftness_potion: {
    id: 'swiftness_potion',
    name: 'Windrunner Elixir',
    category: 'consumable',
    rarity: 'rare',
    maxStack: 16,
    iconColor: '#38bdf8',
    description: 'Grants +35% movement speed and rapid stamina recovery for 60 seconds.',
    staminaRestore: 50,
    consumeTime: 1.2,
    givesEffect: {
      id: 'swiftness',
      duration: 60,
      magnitude: 1,
    },
    baseValue: 40,
  },

  // ==========================================
  // 6. FUNCTIONAL & BUILDING BLOCKS
  // ==========================================
  crafting_bench: {
    id: 'crafting_bench',
    name: 'Artisan Workbench',
    category: 'block',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#8c6740',
    description: 'Enables advanced 3x3 recipe crafting, tool forging, and armor assembly.',
    blockType: BlockType.CRAFTING_BENCH,
    fuelBurnTime: 25,
    baseValue: 6,
  },
  furnace: {
    id: 'furnace',
    name: 'Kiln Smelter',
    category: 'block',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#6e7075',
    description: 'Smelts raw ores and cooks food using coal or timber fuel. Persistent offline smelting.',
    blockType: BlockType.FURNACE,
    baseValue: 12,
  },
  chest: {
    id: 'chest',
    name: 'Reinforced Storage Vault',
    category: 'block',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#856133',
    description: 'Secure storage chest with 27 capacity slots.',
    blockType: BlockType.CHEST,
    fuelBurnTime: 30,
    baseValue: 10,
  },
  anvil_smithing: {
    id: 'anvil_smithing',
    name: 'Forgemaster Smithing Anvil',
    category: 'block',
    rarity: 'uncommon',
    maxStack: 64,
    iconColor: '#474c54',
    description: 'Workstation for repairing damaged tools and forging high-tier alloy enhancements.',
    blockType: BlockType.ANVIL_SMITHING,
    baseValue: 60,
  },
  torch: {
    id: 'torch',
    name: 'Resin Beacon Torch',
    category: 'block',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#f7bf4d',
    description: 'Illuminates dark caves, provides thermal warmth, and deters night predators.',
    blockType: BlockType.TORCH,
    fuelBurnTime: 10,
    baseValue: 1,
  },
  lantern: {
    id: 'lantern',
    name: 'Gilded Lantern',
    category: 'block',
    rarity: 'uncommon',
    maxStack: 64,
    iconColor: '#f2d159',
    description: 'Bright hanging lamp casting warm ambient luminescence.',
    blockType: BlockType.LANTERN,
    baseValue: 15,
  },
  explorer_bed: {
    id: 'explorer_bed',
    name: 'Explorer Rest Cot',
    category: 'block',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#b91c1c',
    description: 'Rest through the nocturnal hours and set respawn location.',
    blockType: BlockType.BED_FOOT,
    baseValue: 18,
  },
  wood_stairs: {
    id: 'wood_stairs',
    name: 'Timber Steps',
    category: 'block',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#9e754c',
    description: 'Carved wooden steps for smooth vertical ascent.',
    blockType: BlockType.WOOD_STAIRS,
    fuelBurnTime: 12,
    baseValue: 2,
  },
  wood_slab: {
    id: 'wood_slab',
    name: 'Timber Half-Block',
    category: 'block',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#9e754c',
    description: 'Half-height plank flooring.',
    blockType: BlockType.WOOD_SLAB,
    fuelBurnTime: 8,
    baseValue: 1,
  },
  stone_stairs: {
    id: 'stone_stairs',
    name: 'Masonry Steps',
    category: 'block',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#7a8085',
    description: 'Hewn stone stairs.',
    blockType: BlockType.STONE_STAIRS,
    baseValue: 2,
  },
  stone_slab: {
    id: 'stone_slab',
    name: 'Masonry Slab',
    category: 'block',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#7a8085',
    description: 'Flat stone slab.',
    blockType: BlockType.STONE_SLAB,
    baseValue: 1,
  },
  wood_fence: {
    id: 'wood_fence',
    name: 'Timber Barrier Fence',
    category: 'block',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#946b42',
    description: 'Perimeter fence to secure livestock and villages.',
    blockType: BlockType.FENCE_WOOD,
    fuelBurnTime: 10,
    baseValue: 2,
  },
  copper_block: {
    id: 'copper_block',
    name: 'Solid Bronze Alloy Block',
    category: 'block',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#d98457',
    description: 'Compressed bronze block for storage and heavy structures.',
    blockType: BlockType.COPPER_BLOCK,
    baseValue: 70,
  },
  iron_block: {
    id: 'iron_block',
    name: 'Forged Ferrite Block',
    category: 'block',
    rarity: 'uncommon',
    maxStack: 64,
    iconColor: '#d1d6dc',
    description: 'Heavy structural iron block.',
    blockType: BlockType.IRON_BLOCK,
    baseValue: 140,
  },
  gold_block: {
    id: 'gold_block',
    name: 'Ingot Aurum Block',
    category: 'block',
    rarity: 'rare',
    maxStack: 64,
    iconColor: '#f2d138',
    description: 'Shining gold block of monumental wealth.',
    blockType: BlockType.GOLD_BLOCK,
    baseValue: 300,
  },
  mythril_block: {
    id: 'mythril_block',
    name: 'Refined Mythril Monolith',
    category: 'block',
    rarity: 'epic',
    maxStack: 64,
    iconColor: '#59b3f2',
    description: 'Glowing astral alloy block.',
    blockType: BlockType.MYTHRIL_BLOCK,
    baseValue: 700,
  },
};
