// Comprehensive Item Registry 2.0: Tier Progression, Tools, Armor Sets, Food Metabolism & Economy
import { BlockType, ItemDef } from '../../types';

export const ITEM_DEFS: Record<string, ItemDef> = {
  // ==========================================
  // 1. RAW MATERIALS, INGOTS & FUEL
  // ==========================================
  wood_planks: {
    id: 'wood_planks',
    name: 'Timber Planks',
    category: 'block',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#9e754c',
    description: 'Sturdy wooden building boards.',
    blockType: BlockType.WOOD_PLANKS,
    fuelBurnTime: 15,
    baseValue: 1,
  },
  oak_log: {
    id: 'oak_log',
    name: 'Ancient Oak Log',
    category: 'block',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#604229',
    description: 'Raw oak timber felled from primeval groves.',
    blockType: BlockType.OAK_LOG,
    fuelBurnTime: 30,
    baseValue: 4,
  },
  pine_log: {
    id: 'pine_log',
    name: 'Boreal Pine Log',
    category: 'block',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#473324',
    description: 'Dense fragrant pine wood.',
    blockType: BlockType.PINE_LOG,
    fuelBurnTime: 30,
    baseValue: 4,
  },
  aether_log: {
    id: 'aether_log',
    name: 'Aetherwood Stem',
    category: 'block',
    rarity: 'rare',
    maxStack: 64,
    iconColor: '#403361',
    description: 'Mystical crystal-infused wood infused with arcane ley energy.',
    blockType: BlockType.CYAN_CRYSTAL_LOG,
    fuelBurnTime: 60,
    baseValue: 12,
  },
  // Crops & Farming Supplies
  wheat: {
    id: 'wheat',
    name: 'Golden Wheat Sheaf',
    category: 'material',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#e0b848',
    description: 'Harvested grain used for baking bread, crafting animal feed, and breeding livestock.',
    baseValue: 2,
  },
  potato: {
    id: 'potato',
    name: 'Wild Starch Potato',
    category: 'food',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#8f683a',
    description: 'Nutritious root vegetable suitable for cooking and stews.',
    foodValue: 12,
    foodRestoration: 12,
    baseValue: 2,
  },
  stick: {
    id: 'stick',
    name: 'Carved Wooden Rod',
    category: 'material',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#8c6747',
    description: 'Basic crafting handle used for tools and weapons.',
    fuelBurnTime: 5,
    baseValue: 1,
  },
  dirt: {
    id: 'dirt',
    name: 'Rich Soil',
    category: 'block',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#704d2e',
    description: 'Fertile earth suitable for farming with a hoe.',
    blockType: BlockType.DIRT,
    baseValue: 1,
  },
  sand: {
    id: 'sand',
    name: 'Golden Sand',
    category: 'block',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#dbc785',
    description: 'Fine quartz particles. Smelt in a kiln to make silica glass.',
    blockType: BlockType.SAND,
    baseValue: 1,
  },
  gravel: {
    id: 'gravel',
    name: 'River Shingle',
    category: 'block',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#8c8a85',
    description: 'Loose shingle that can yield flint shards.',
    blockType: BlockType.GRAVEL,
    baseValue: 1,
  },
  flint: {
    id: 'flint',
    name: 'Fractured Flint Shard',
    category: 'material',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#3d3e42',
    description: 'Sharp sedimentary stone used for arrows and crude tools.',
    baseValue: 2,
  },
  clay_ball: {
    id: 'clay_ball',
    name: 'Terracotta Clay Lump',
    category: 'material',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#a66e53',
    description: 'Soft sediment malleable for kiln firing.',
    baseValue: 2,
  },
  brick: {
    id: 'brick',
    name: 'Kiln Fired Brick',
    category: 'material',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#b34a36',
    description: 'Hardened masonry brick for fireproof structures.',
    baseValue: 3,
  },
  stone: {
    id: 'stone',
    name: 'Smooth Stone',
    category: 'block',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#808285',
    description: 'Smelted stone block suitable for stone masonry.',
    blockType: BlockType.STONE,
    baseValue: 1,
  },
  cobblestone: {
    id: 'cobblestone',
    name: 'Fractured Cobble',
    category: 'block',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#73757a',
    description: 'Rough stone blocks suitable for basic construction.',
    blockType: BlockType.COBBLESTONE,
    baseValue: 1,
  },
  stone_bricks: {
    id: 'stone_bricks',
    name: 'Carved Masonry Bricks',
    category: 'block',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#7a8085',
    description: 'Polished dressed stone blocks.',
    blockType: BlockType.STONE_BRICKS,
    baseValue: 2,
  },
  stone_pillar: {
    id: 'stone_pillar',
    name: 'Carved Colonnade Pillar',
    category: 'block',
    rarity: 'uncommon',
    maxStack: 64,
    iconColor: '#8c8f94',
    description: 'Architectural column for grand temples and vaulted ceilings.',
    blockType: BlockType.STONE_PILLAR,
    baseValue: 3,
  },
  glass: {
    id: 'glass',
    name: 'Silica Glass',
    category: 'block',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#b8e0f2',
    description: 'Transparent tempered window pane.',
    blockType: BlockType.GLASS,
    baseValue: 3,
  },
  coal: {
    id: 'coal',
    name: 'Carbon Bitumen Lump',
    category: 'material',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#2b2c30',
    description: 'High-energy smelting fuel providing 80s of burn time.',
    fuelBurnTime: 80,
    baseValue: 4,
  },
  charcoal: {
    id: 'charcoal',
    name: 'Pyrolyzed Charcoal',
    category: 'material',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#36373b',
    description: 'Smelted timber charcoal providing 70s of burn time.',
    fuelBurnTime: 70,
    baseValue: 3,
  },
  raw_copper: {
    id: 'raw_copper',
    name: 'Raw Cuprite Ore',
    category: 'material',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#8c5947',
    description: 'Unrefined copper mineral. Smelt in a kiln to produce ingots.',
    baseValue: 4,
  },
  copper_ingot: {
    id: 'copper_ingot',
    name: 'Forged Bronze Ingot',
    category: 'material',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#d98457',
    description: 'Ductile metallic bar used for Tier 1 tools and armor.',
    baseValue: 8,
  },
  raw_iron: {
    id: 'raw_iron',
    name: 'Raw Hematite Ore',
    category: 'material',
    rarity: 'uncommon',
    maxStack: 64,
    iconColor: '#998c80',
    description: 'Dense magnetic iron chunk.',
    baseValue: 8,
  },
  iron_ingot: {
    id: 'iron_ingot',
    name: 'Ferrite Steel Ingot',
    category: 'material',
    rarity: 'uncommon',
    maxStack: 64,
    iconColor: '#d1d6dc',
    description: 'Hardened structural metal for Tier 2 gear.',
    baseValue: 16,
  },
  raw_gold: {
    id: 'raw_gold',
    name: 'Raw Aurum Ore',
    category: 'material',
    rarity: 'rare',
    maxStack: 64,
    iconColor: '#c2a54d',
    description: 'Precious metallic cluster found in deep chasms.',
    baseValue: 18,
  },
  gold_ingot: {
    id: 'gold_ingot',
    name: 'Refined Aurum Bar',
    category: 'material',
    rarity: 'rare',
    maxStack: 64,
    iconColor: '#f2d138',
    description: 'Conductive precious ingot for enchantments, crowns, and relics.',
    baseValue: 35,
  },
  raw_mythril: {
    id: 'raw_mythril',
    name: 'Raw Mythril Ore',
    category: 'material',
    rarity: 'epic',
    maxStack: 64,
    iconColor: '#4d99d9',
    description: 'Ultra-light celestial metallic ore found in deep abyss chasms.',
    baseValue: 40,
  },
  mythril_ingot: {
    id: 'mythril_ingot',
    name: 'Astral Mythril Ingot',
    category: 'material',
    rarity: 'epic',
    maxStack: 64,
    iconColor: '#59b3f2',
    description: 'Pristine Tier 3 metal with supreme durability and razor sharpness.',
    baseValue: 80,
  },
  aether_crystal: {
    id: 'aether_crystal',
    name: 'Aether Prism Shard',
    category: 'material',
    rarity: 'legendary',
    maxStack: 64,
    iconColor: '#b359e6',
    description: 'Pure concentrated magical energy resonating from cosmic rifts.',
    baseValue: 150,
  },
  ancient_alloy: {
    id: 'ancient_alloy',
    name: 'Titanforged Astral Core',
    category: 'material',
    rarity: 'ancient',
    maxStack: 16,
    iconColor: '#2ae8c8',
    description: 'Relic metallurgical wonder from the lost builders of the realm.',
    baseValue: 300,
  },
  ancient_tome: {
    id: 'ancient_tome',
    name: 'Archivist Codex',
    category: 'material',
    rarity: 'rare',
    maxStack: 16,
    iconColor: '#5c4530',
    description: 'Bound parchment containing lost architectural formulae.',
    baseValue: 25,
  },
  leather_pelt: {
    id: 'leather_pelt',
    name: 'Tanned Beast Hide',
    category: 'material',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#8a5229',
    description: 'Supple warm hide for leather armor and backpacks.',
    baseValue: 5,
  },
  monster_bone: {
    id: 'monster_bone',
    name: 'Grave Fiend Bone',
    category: 'material',
    rarity: 'uncommon',
    maxStack: 64,
    iconColor: '#e0dedb',
    description: 'Hardened ossified material. Can be crushed into bone meal fertilizer.',
    baseValue: 6,
  },
  feather: {
    id: 'feather',
    name: 'Highland Gryphon Plume',
    category: 'material',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#d6d2c4',
    description: 'Aerodynamic fletching for projectile craft.',
    baseValue: 2,
  },

  // ==========================================
  // 2. TOOLS & HARVESTING GEAR
  // ==========================================
  // Pickaxes
  wooden_pickaxe: {
    id: 'wooden_pickaxe',
    name: 'Timber Pickaxe',
    category: 'tool',
    rarity: 'common',
    maxStack: 1,
    iconColor: '#a67b51',
    description: 'Basic mining tool for excavating soft stone and copper ore.',
    toolType: 'pickaxe',
    tier: 0,
    miningEfficiency: 1.8,
    attackDamage: 3,
    attackSpeed: 1.2,
    durability: 60,
    repairMaterial: 'wood_planks',
    baseValue: 5,
  },
  stone_pickaxe: {
    id: 'stone_pickaxe',
    name: 'Cobble Pickaxe',
    category: 'tool',
    rarity: 'common',
    maxStack: 1,
    iconColor: '#7a7c80',
    description: 'Flint-tipped stone pickaxe. Good early workhorse.',
    toolType: 'pickaxe',
    tier: 0,
    miningEfficiency: 2.6,
    attackDamage: 4,
    attackSpeed: 1.2,
    durability: 120,
    repairMaterial: 'cobblestone',
    baseValue: 8,
  },
  copper_pickaxe: {
    id: 'copper_pickaxe',
    name: 'Bronze Pickaxe',
    category: 'tool',
    rarity: 'common',
    maxStack: 1,
    iconColor: '#d98457',
    description: 'Sturdy bronze pick capable of mining iron ore.',
    toolType: 'pickaxe',
    tier: 1,
    miningEfficiency: 4.2,
    attackDamage: 5,
    attackSpeed: 1.2,
    durability: 200,
    repairMaterial: 'copper_ingot',
    baseValue: 20,
  },
  iron_pickaxe: {
    id: 'iron_pickaxe',
    name: 'Ferrite Pickaxe',
    category: 'tool',
    rarity: 'uncommon',
    maxStack: 1,
    iconColor: '#d1d6dc',
    description: 'Heavy duty steel pick for gold and deep subterranean stone.',
    toolType: 'pickaxe',
    tier: 2,
    miningEfficiency: 6.8,
    attackDamage: 7,
    attackSpeed: 1.2,
    durability: 450,
    repairMaterial: 'iron_ingot',
    baseValue: 45,
  },
  mythril_pickaxe: {
    id: 'mythril_pickaxe',
    name: 'Astral Mythril Pickaxe',
    category: 'tool',
    rarity: 'epic',
    maxStack: 1,
    iconColor: '#59b3f2',
    description: 'Weightless crystalline pick that shreds obsidian and geodes.',
    toolType: 'pickaxe',
    tier: 3,
    miningEfficiency: 11.0,
    attackDamage: 10,
    attackSpeed: 1.3,
    durability: 1100,
    repairMaterial: 'mythril_ingot',
    baseValue: 180,
  },
  aether_pickaxe: {
    id: 'aether_pickaxe',
    name: 'Titanforged Void Pickaxe',
    category: 'tool',
    rarity: 'legendary',
    maxStack: 1,
    iconColor: '#a855f7',
    description: 'Cosmic tool that fractures bedrock and instant-excavates veins.',
    toolType: 'pickaxe',
    tier: 4,
    miningEfficiency: 16.0,
    attackDamage: 14,
    attackSpeed: 1.4,
    durability: 2500,
    repairMaterial: 'aether_crystal',
    baseValue: 400,
  },

  // Axes
  wooden_axe: {
    id: 'wooden_axe',
    name: 'Timber Hatchet',
    category: 'tool',
    rarity: 'common',
    maxStack: 1,
    iconColor: '#a67b51',
    description: 'Harvests timber and chops logs quickly.',
    toolType: 'axe',
    tier: 0,
    miningEfficiency: 2.0,
    attackDamage: 5,
    attackSpeed: 1.0,
    durability: 60,
    repairMaterial: 'wood_planks',
    baseValue: 5,
  },
  copper_axe: {
    id: 'copper_axe',
    name: 'Bronze Felling Axe',
    category: 'tool',
    rarity: 'common',
    maxStack: 1,
    iconColor: '#d98457',
    description: 'Sharp bronze axe for rapid lumberjack forestry.',
    toolType: 'axe',
    tier: 1,
    miningEfficiency: 4.2,
    attackDamage: 8,
    attackSpeed: 1.0,
    durability: 200,
    repairMaterial: 'copper_ingot',
    baseValue: 20,
  },
  iron_axe: {
    id: 'iron_axe',
    name: 'Forged Battle-Axe',
    category: 'tool',
    rarity: 'uncommon',
    maxStack: 1,
    iconColor: '#d1d6dc',
    description: 'Powerful lumber tool and heavy cleaving weapon.',
    toolType: 'axe',
    tier: 2,
    miningEfficiency: 7.0,
    attackDamage: 14,
    attackSpeed: 0.9,
    durability: 450,
    repairMaterial: 'iron_ingot',
    baseValue: 45,
  },
  mythril_axe: {
    id: 'mythril_axe',
    name: 'Astral War-Axe',
    category: 'tool',
    rarity: 'epic',
    maxStack: 1,
    iconColor: '#59b3f2',
    description: 'Celestial axe with unmatched cutting precision.',
    toolType: 'axe',
    tier: 3,
    miningEfficiency: 11.5,
    attackDamage: 20,
    attackSpeed: 1.0,
    durability: 1100,
    repairMaterial: 'mythril_ingot',
    baseValue: 180,
  },

  // Shovels
  wooden_shovel: {
    id: 'wooden_shovel',
    name: 'Timber Spade',
    category: 'tool',
    rarity: 'common',
    maxStack: 1,
    iconColor: '#a67b51',
    description: 'Excavates dirt, sand, and gravel rapidly.',
    toolType: 'shovel',
    tier: 0,
    miningEfficiency: 2.5,
    attackDamage: 2,
    durability: 60,
    repairMaterial: 'wood_planks',
    baseValue: 3,
  },
  copper_shovel: {
    id: 'copper_shovel',
    name: 'Bronze Excavator',
    category: 'tool',
    rarity: 'common',
    maxStack: 1,
    iconColor: '#d98457',
    description: 'Reinforced bronze shovel for terrain landscaping.',
    toolType: 'shovel',
    tier: 1,
    miningEfficiency: 5.0,
    attackDamage: 4,
    durability: 200,
    repairMaterial: 'copper_ingot',
    baseValue: 15,
  },
  iron_shovel: {
    id: 'iron_shovel',
    name: 'Steel Trench Spade',
    category: 'tool',
    rarity: 'uncommon',
    maxStack: 1,
    iconColor: '#d1d6dc',
    description: 'Reinforced spade for high-speed terraforming.',
    toolType: 'shovel',
    tier: 2,
    miningEfficiency: 8.0,
    attackDamage: 6,
    durability: 450,
    repairMaterial: 'iron_ingot',
    baseValue: 35,
  },

  // Hoes & Farming Tools
  wooden_hoe: {
    id: 'wooden_hoe',
    name: 'Timber Cultivator',
    category: 'tool',
    rarity: 'common',
    maxStack: 1,
    iconColor: '#a67b51',
    description: 'Tills grass and soil into fertile farmland for crops.',
    toolType: 'hoe',
    tier: 0,
    durability: 60,
    repairMaterial: 'wood_planks',
    baseValue: 4,
  },
  iron_hoe: {
    id: 'iron_hoe',
    name: 'Ferrite Agricultural Hoe',
    category: 'tool',
    rarity: 'uncommon',
    maxStack: 1,
    iconColor: '#d1d6dc',
    description: 'Durable steel farming tool for extensive crop fields.',
    toolType: 'hoe',
    tier: 2,
    durability: 400,
    repairMaterial: 'iron_ingot',
    baseValue: 30,
  },

  // ==========================================
  // 3. WEAPONS & COMBAT
  // ==========================================
  wooden_sword: {
    id: 'wooden_sword',
    name: 'Hardwood Practice Blade',
    category: 'weapon',
    rarity: 'common',
    maxStack: 1,
    iconColor: '#8a623a',
    description: 'Light wooden sword for fending off small nocturnal beasts.',
    attackDamage: 6,
    attackSpeed: 1.6,
    durability: 55,
    repairMaterial: 'wood_planks',
    baseValue: 4,
  },
  copper_blade: {
    id: 'copper_blade',
    name: 'Bronze Gladius',
    category: 'weapon',
    rarity: 'common',
    maxStack: 1,
    iconColor: '#d98457',
    description: 'Swift balanced blade for melee encounters.',
    attackDamage: 12,
    attackSpeed: 1.6,
    durability: 180,
    repairMaterial: 'copper_ingot',
    baseValue: 18,
  },
  iron_blade: {
    id: 'iron_blade',
    name: 'Ferrite Longsword',
    category: 'weapon',
    rarity: 'uncommon',
    maxStack: 1,
    iconColor: '#d1d6dc',
    description: 'Tempered steel blade dealing devastating sweeping strikes.',
    attackDamage: 20,
    attackSpeed: 1.5,
    durability: 380,
    repairMaterial: 'iron_ingot',
    baseValue: 42,
  },
  mythril_saber: {
    id: 'mythril_saber',
    name: 'Astral Mythril Saber',
    category: 'weapon',
    rarity: 'epic',
    maxStack: 1,
    iconColor: '#59b3f2',
    description: 'Bladesmith masterpiece humming with celestial radiance.',
    attackDamage: 32,
    attackSpeed: 1.8,
    durability: 950,
    repairMaterial: 'mythril_ingot',
    baseValue: 190,
  },
  aether_staff: {
    id: 'aether_staff',
    name: 'Prismatic Archon Staff',
    category: 'weapon',
    rarity: 'legendary',
    maxStack: 1,
    iconColor: '#b359e6',
    description: 'Harnesses raw arcane vortex bolts against distant enemies.',
    attackDamage: 45,
    attackSpeed: 1.2,
    durability: 1400,
    repairMaterial: 'aether_crystal',
    baseValue: 450,
  },
  hunting_bow: {
    id: 'hunting_bow',
    name: 'Recurve Hunting Bow',
    category: 'weapon',
    rarity: 'common',
    maxStack: 1,
    iconColor: '#785334',
    description: 'Flexible composite bow for long-range precision shots.',
    attackDamage: 16,
    attackSpeed: 1.0,
    durability: 150,
    repairMaterial: 'wood_planks',
    baseValue: 16,
  },
  wooden_arrow: {
    id: 'wooden_arrow',
    name: 'Flint-Headed Arrow',
    category: 'material',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#9c9287',
    description: 'Standard ammunition fired from bows.',
    baseValue: 1,
  },

  // ==========================================
  // 4. ARMOR SETS (Defense & Survival Insulation)
  // ==========================================
  // Leather Set (Tier 0 / Thermal Warmth)
  leather_cap: {
    id: 'leather_cap',
    name: 'Trapper Fur Hood',
    category: 'armor',
    armorSlot: 'head',
    rarity: 'common',
    maxStack: 1,
    iconColor: '#8a5229',
    description: 'Warm fur-lined hood. Offers basic protection and cold insulation.',
    armorValue: 4,
    durability: 80,
    repairMaterial: 'leather_pelt',
    baseValue: 8,
  },
  leather_tunic: {
    id: 'leather_tunic',
    name: 'Trapper Leather Vest',
    category: 'armor',
    armorSlot: 'chest',
    rarity: 'common',
    maxStack: 1,
    iconColor: '#8a5229',
    description: 'Supple chest vest providing cold insulation.',
    armorValue: 8,
    durability: 120,
    repairMaterial: 'leather_pelt',
    baseValue: 14,
  },
  leather_pants: {
    id: 'leather_pants',
    name: 'Trapper Hide Breeches',
    category: 'armor',
    armorSlot: 'legs',
    rarity: 'common',
    maxStack: 1,
    iconColor: '#8a5229',
    description: 'Flexible leather pants for wilderness exploration.',
    armorValue: 6,
    durability: 100,
    repairMaterial: 'leather_pelt',
    baseValue: 11,
  },
  leather_boots: {
    id: 'leather_boots',
    name: 'Trapper Moccasins',
    category: 'armor',
    armorSlot: 'feet',
    rarity: 'common',
    maxStack: 1,
    iconColor: '#8a5229',
    description: 'Light soft-sole boots that reduce fall damage slightly.',
    armorValue: 3,
    durability: 75,
    repairMaterial: 'leather_pelt',
    baseValue: 7,
  },

  // Copper / Bronze Set (Tier 1)
  copper_helmet: {
    id: 'copper_helmet',
    name: 'Bronze Hoplite Sallet',
    category: 'armor',
    armorSlot: 'head',
    rarity: 'common',
    maxStack: 1,
    iconColor: '#d98457',
    description: 'Shining bronze helmet with protective cheekguards.',
    armorValue: 8,
    durability: 140,
    repairMaterial: 'copper_ingot',
    baseValue: 18,
  },
  copper_chestplate: {
    id: 'copper_chestplate',
    name: 'Bronze Hoplite Cuirass',
    category: 'armor',
    armorSlot: 'chest',
    rarity: 'common',
    maxStack: 1,
    iconColor: '#d98457',
    description: 'Hand-hammered bronze breastplate.',
    armorValue: 16,
    durability: 200,
    repairMaterial: 'copper_ingot',
    baseValue: 32,
  },
  copper_greaves: {
    id: 'copper_greaves',
    name: 'Bronze Hoplite Greaves',
    category: 'armor',
    armorSlot: 'legs',
    rarity: 'common',
    maxStack: 1,
    iconColor: '#d98457',
    description: 'Articulated bronze leg protection.',
    armorValue: 12,
    durability: 180,
    repairMaterial: 'copper_ingot',
    baseValue: 24,
  },
  copper_boots: {
    id: 'copper_boots',
    name: 'Bronze Hoplite Sabatons',
    category: 'armor',
    armorSlot: 'feet',
    rarity: 'common',
    maxStack: 1,
    iconColor: '#d98457',
    description: 'Reinforced bronze boots.',
    armorValue: 6,
    durability: 120,
    repairMaterial: 'copper_ingot',
    baseValue: 15,
  },

  // Iron / Ferrite Set (Tier 2)
  iron_helmet: {
    id: 'iron_helmet',
    name: 'Ferrite Greathelm',
    category: 'armor',
    armorSlot: 'head',
    rarity: 'uncommon',
    maxStack: 1,
    iconColor: '#d1d6dc',
    description: 'Steel cranial guard with reinforced visor.',
    armorValue: 14,
    durability: 220,
    repairMaterial: 'iron_ingot',
    baseValue: 35,
  },
  iron_chestplate: {
    id: 'iron_chestplate',
    name: 'Ferrite Cuirass',
    category: 'armor',
    armorSlot: 'chest',
    rarity: 'uncommon',
    maxStack: 1,
    iconColor: '#d1d6dc',
    description: 'Solid heavy breastplate protecting vital organs.',
    armorValue: 28,
    durability: 350,
    repairMaterial: 'iron_ingot',
    baseValue: 65,
  },
  iron_greaves: {
    id: 'iron_greaves',
    name: 'Ferrite Greaves',
    category: 'armor',
    armorSlot: 'legs',
    rarity: 'uncommon',
    maxStack: 1,
    iconColor: '#d1d6dc',
    description: 'Articulated plate armor for the legs.',
    armorValue: 20,
    durability: 300,
    repairMaterial: 'iron_ingot',
    baseValue: 50,
  },
  iron_boots: {
    id: 'iron_boots',
    name: 'Ferrite Sabatons',
    category: 'armor',
    armorSlot: 'feet',
    rarity: 'uncommon',
    maxStack: 1,
    iconColor: '#d1d6dc',
    description: 'Heavy steel footwear giving steady footing.',
    armorValue: 12,
    durability: 200,
    repairMaterial: 'iron_ingot',
    baseValue: 30,
  },

  // Mythril Astral Set (Tier 3)
  mythril_helmet: {
    id: 'mythril_helmet',
    name: 'Astral Mythril Diadem',
    category: 'armor',
    armorSlot: 'head',
    rarity: 'epic',
    maxStack: 1,
    iconColor: '#59b3f2',
    description: 'Crown forged of lightweight celestial alloy.',
    armorValue: 22,
    durability: 600,
    repairMaterial: 'mythril_ingot',
    baseValue: 140,
  },
  mythril_chestplate: {
    id: 'mythril_chestplate',
    name: 'Astral Mythril Plate',
    category: 'armor',
    armorSlot: 'chest',
    rarity: 'epic',
    maxStack: 1,
    iconColor: '#59b3f2',
    description: 'Superb chestplate repelling powerful blows effortlessly.',
    armorValue: 42,
    durability: 900,
    repairMaterial: 'mythril_ingot',
    baseValue: 280,
  },
  mythril_greaves: {
    id: 'mythril_greaves',
    name: 'Astral Mythril Legguards',
    category: 'armor',
    armorSlot: 'legs',
    rarity: 'epic',
    maxStack: 1,
    iconColor: '#59b3f2',
    description: 'Featherlight combat greaves.',
    armorValue: 30,
    durability: 750,
    repairMaterial: 'mythril_ingot',
    baseValue: 210,
  },
  mythril_boots: {
    id: 'mythril_boots',
    name: 'Astral Mythril Greaves',
    category: 'armor',
    armorSlot: 'feet',
    rarity: 'epic',
    maxStack: 1,
    iconColor: '#59b3f2',
    description: 'Empowers sprint speed and reduces fall damage.',
    armorValue: 18,
    durability: 550,
    repairMaterial: 'mythril_ingot',
    baseValue: 130,
  },

  // Relic Accessories
  ring_of_vitality: {
    id: 'ring_of_vitality',
    name: 'Amulet of the Sun Ward',
    category: 'accessory',
    armorSlot: 'accessory',
    rarity: 'rare',
    maxStack: 1,
    iconColor: '#f59e0b',
    description: 'Ancient pendant that grants +25 Max Health and thermal resistance.',
    armorValue: 8,
    givesEffect: {
      id: 'regeneration',
      duration: 300,
      magnitude: 1,
    },
    baseValue: 150,
  },

  eye_of_aether: {
    id: 'eye_of_aether',
    name: 'Eye of the Aetherborn',
    category: 'accessory',
    armorSlot: 'accessory',
    rarity: 'epic',
    maxStack: 1,
    iconColor: '#38bdf8',
    description: 'Relic: Pulsing orb that grants continuous soft regeneration and illumination.',
    armorValue: 10,
    givesEffect: {
      id: 'regeneration',
      duration: 9999,
      magnitude: 1,
    },
    baseValue: 400,
  },
  chrono_core: {
    id: 'chrono_core',
    name: 'Perpetual Chrono Core',
    category: 'accessory',
    armorSlot: 'accessory',
    rarity: 'epic',
    maxStack: 1,
    iconColor: '#fbbf24',
    description: 'Relic: Kinetic heart. Substantially increases energy and movement speed.',
    armorValue: 10,
    baseValue: 500,
  },
  solaris_aegis: {
    id: 'solaris_aegis',
    name: 'Solaris Aegis Medallion',
    category: 'accessory',
    armorSlot: 'accessory',
    rarity: 'legendary',
    maxStack: 1,
    iconColor: '#f97316',
    description: 'Relic: Medallion forged from magma crystals, offering immense defense.',
    armorValue: 35,
    baseValue: 800,
  },
  tidal_pearl: {
    id: 'tidal_pearl',
    name: 'Pearl of the Abyssal Siren',
    category: 'accessory',
    armorSlot: 'accessory',
    rarity: 'epic',
    maxStack: 1,
    iconColor: '#2dd4bf',
    description: 'Relic: Siren relic that increases underwater oxygen capacity and speed.',
    armorValue: 12,
    baseValue: 450,
  },
  void_walker_ring: {
    id: 'void_walker_ring',
    name: 'Ring of the Void Sovereign',
    category: 'accessory',
    armorSlot: 'accessory',
    rarity: 'ancient',
    maxStack: 1,
    iconColor: '#c084fc',
    description: 'Relic: Sovereign band granting dark energy immunity and critical defense.',
    armorValue: 45,
    baseValue: 1200,
  },
  precursor_matrix: {
    id: 'precursor_matrix',
    name: 'Precursor Knowledge Matrix',
    category: 'accessory',
    armorSlot: 'accessory',
    rarity: 'ancient',
    maxStack: 1,
    iconColor: '#ec4899',
    description: 'Relic: floating memory matrix unlocking masterwork blueprints and shields.',
    armorValue: 20,
    baseValue: 1500,
  },

  // ==========================================
  // 5. FOOD, FARMING SEEDS & CONSUMABLES
  // ==========================================
  seeds_wheat: {
    id: 'seeds_wheat',
    name: 'Golden Grain Seeds',
    category: 'seed',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#c4b574',
    description: 'Plant on tilled farmland soil to grow wheat.',
    baseValue: 1,
  },
  crop_wheat: {
    id: 'crop_wheat',
    name: 'Harvested Golden Grain',
    category: 'material',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#e0c058',
    description: 'Ripe wheat sheaves ready to be ground into flour and baked into bread.',
    baseValue: 2,
  },
  wild_carrot: {
    id: 'wild_carrot',
    name: 'Wild Ember Carrot',
    category: 'food',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#f97316',
    description: 'Crunchy vitamin-rich root. Restores 22 Hunger and 15 Saturation.',
    foodValue: 22,
    saturationValue: 15,
    staminaRestore: 12,
    consumeTime: 1.5,
    baseValue: 3,
  },
  crop_potato: {
    id: 'crop_potato',
    name: 'Highland Russet Potato',
    category: 'food',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#a88151',
    description: 'Dense starchy tuber. Smelt in kiln for delicious baked potato.',
    foodValue: 18,
    saturationValue: 10,
    staminaRestore: 10,
    consumeTime: 1.5,
    baseValue: 2,
  },
  baked_potato: {
    id: 'baked_potato',
    name: 'Kiln-Roasted Potato',
    category: 'food',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#c49a62',
    description: 'Warm roasted potato providing comfort in cold biomes. Restores 38 Hunger.',
    foodValue: 38,
    saturationValue: 28,
    staminaRestore: 25,
    healValue: 5,
    consumeTime: 1.4,
    baseValue: 5,
  },
  crop_herb: {
    id: 'crop_herb',
    name: 'Astral Healing Herb',
    category: 'material',
    rarity: 'uncommon',
    maxStack: 64,
    iconColor: '#10b981',
    description: 'Medicinal leaf utilized in vitality elixirs and soothing teas.',
    baseValue: 5,
  },
  berries: {
    id: 'berries',
    name: 'Crimson Sun Berries',
    category: 'food',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#e63946',
    description: 'Juicy wild berries harvested from meadow bushes. Restores 16 Hunger.',
    foodValue: 16,
    saturationValue: 8,
    staminaRestore: 12,
    consumeTime: 1.2,
    baseValue: 2,
  },
  bread: {
    id: 'bread',
    name: 'Hearth Loaf',
    category: 'food',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#d4a373',
    description: 'Baked wheat loaf. Restores 40 Hunger and 35 Saturation.',
    foodValue: 40,
    saturationValue: 35,
    staminaRestore: 30,
    healValue: 8,
    consumeTime: 1.6,
    baseValue: 6,
  },
  raw_meat: {
    id: 'raw_meat',
    name: 'Raw Primeval Game Meat',
    category: 'food',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#8a2b2b',
    description: 'Uncooked meat cut from wild game. Best cooked to avoid parasite weakness.',
    foodValue: 18,
    saturationValue: 8,
    staminaRestore: 10,
    consumeTime: 1.8,
    baseValue: 4,
  },
  cooked_meat: {
    id: 'cooked_meat',
    name: 'Roasted Stag Tenderloin',
    category: 'food',
    rarity: 'uncommon',
    maxStack: 64,
    iconColor: '#9c412b',
    description: 'Hearty roasted cut providing sustained vigor. Restores 60 Hunger and 50 Saturation.',
    foodValue: 60,
    saturationValue: 50,
    staminaRestore: 45,
    healValue: 18,
    consumeTime: 1.8,
    givesEffect: {
      id: 'well_fed',
      duration: 60,
      magnitude: 1,
    },
    baseValue: 12,
  },
  raw_fish: {
    id: 'raw_fish',
    name: 'Raw Silver Tide Fish',
    category: 'food',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#7a9fb8',
    description: 'Fresh river catch with shimmering scales.',
    foodValue: 15,
    saturationValue: 6,
    staminaRestore: 10,
    consumeTime: 1.5,
    baseValue: 3,
  },
  cooked_fish: {
    id: 'cooked_fish',
    name: 'Seared Silver Fillet',
    category: 'food',
    rarity: 'uncommon',
    maxStack: 64,
    iconColor: '#d68e58',
    description: 'Crisp seared river fish providing rich omega vitality.',
    foodValue: 48,
    saturationValue: 38,
    staminaRestore: 35,
    healValue: 12,
    consumeTime: 1.5,
    baseValue: 9,
  },
  hearty_stew: {
    id: 'hearty_stew',
    name: 'Nomad Forest Stew',
    category: 'food',
    rarity: 'rare',
    maxStack: 16,
    iconColor: '#854d0e',
    description: 'Slow-simmered vegetable and meat stew. Restores 85 Hunger, 70 Saturation, and 30 Health.',
    foodValue: 85,
    saturationValue: 70,
    staminaRestore: 60,
    healValue: 30,
    consumeTime: 2.2,
    givesEffect: {
      id: 'well_fed',
      duration: 120,
      magnitude: 2,
    },
    baseValue: 25,
  },
  golden_fruit: {
    id: 'golden_fruit',
    name: 'Auric Ambrosia Apple',
    category: 'food',
    rarity: 'legendary',
    maxStack: 16,
    iconColor: '#facc15',
    description: 'Legendary orchard harvest granting instant full recovery, regeneration, and damage boost.',
    foodValue: 100,
    saturationValue: 100,
    staminaRestore: 100,
    healValue: 75,
    consumeTime: 1.5,
    givesEffect: {
      id: 'regeneration',
      duration: 30,
      magnitude: 3,
    },
    baseValue: 200,
  },
  healing_potion: {
    id: 'healing_potion',
    name: 'Vitality Draught',
    category: 'consumable',
    rarity: 'rare',
    maxStack: 16,
    iconColor: '#10b981',
    description: 'Alchemical tincture that instantly restores 50 Health and cures poison.',
    healValue: 50,
    staminaRestore: 25,
    consumeTime: 1.2,
    givesEffect: {
      id: 'regeneration',
      duration: 15,
      magnitude: 2,
    },
    baseValue: 35,
  },
  swiftness_potion: {
    id: 'swiftness_potion',
    name: 'Windrunner Elixir',
    category: 'consumable',
    rarity: 'rare',
    maxStack: 16,
    iconColor: '#38bdf8',
    description: 'Grants +35% movement speed and rapid stamina recovery for 60 seconds.',
    staminaRestore: 50,
    consumeTime: 1.2,
    givesEffect: {
      id: 'swiftness',
      duration: 60,
      magnitude: 1,
    },
    baseValue: 40,
  },

  // ==========================================
  // 6. FUNCTIONAL & BUILDING BLOCKS
  // ==========================================
  crafting_bench: {
    id: 'crafting_bench',
    name: 'Artisan Workbench',
    category: 'block',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#8c6740',
    description: 'Enables advanced 3x3 recipe crafting, tool forging, and armor assembly.',
    blockType: BlockType.CRAFTING_BENCH,
    fuelBurnTime: 25,
    baseValue: 6,
  },
  furnace: {
    id: 'furnace',
    name: 'Kiln Smelter',
    category: 'block',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#6e7075',
    description: 'Smelts raw ores and cooks food using coal or timber fuel. Persistent offline smelting.',
    blockType: BlockType.FURNACE,
    baseValue: 12,
  },
  chest: {
    id: 'chest',
    name: 'Reinforced Storage Vault',
    category: 'block',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#856133',
    description: 'Secure storage chest with 27 capacity slots.',
    blockType: BlockType.CHEST,
    fuelBurnTime: 30,
    baseValue: 10,
  },
  anvil_smithing: {
    id: 'anvil_smithing',
    name: 'Forgemaster Smithing Anvil',
    category: 'block',
    rarity: 'uncommon',
    maxStack: 64,
    iconColor: '#474c54',
    description: 'Workstation for repairing damaged tools and forging high-tier alloy enhancements.',
    blockType: BlockType.ANVIL_SMITHING,
    baseValue: 60,
  },
  torch: {
    id: 'torch',
    name: 'Resin Beacon Torch',
    category: 'block',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#f7bf4d',
    description: 'Illuminates dark caves, provides thermal warmth, and deters night predators.',
    blockType: BlockType.TORCH,
    fuelBurnTime: 10,
    baseValue: 1,
  },
  lantern: {
    id: 'lantern',
    name: 'Gilded Lantern',
    category: 'block',
    rarity: 'uncommon',
    maxStack: 64,
    iconColor: '#f2d159',
    description: 'Bright hanging lamp casting warm ambient luminescence.',
    blockType: BlockType.LANTERN,
    baseValue: 15,
  },
  explorer_bed: {
    id: 'explorer_bed',
    name: 'Explorer Rest Cot',
    category: 'block',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#b91c1c',
    description: 'Rest through the nocturnal hours and set respawn location.',
    blockType: BlockType.BED_FOOT,
    baseValue: 18,
  },
  wood_stairs: {
    id: 'wood_stairs',
    name: 'Timber Steps',
    category: 'block',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#9e754c',
    description: 'Carved wooden steps for smooth vertical ascent.',
    blockType: BlockType.WOOD_STAIRS,
    fuelBurnTime: 12,
    baseValue: 2,
  },
  wood_slab: {
    id: 'wood_slab',
    name: 'Timber Half-Block',
    category: 'block',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#9e754c',
    description: 'Half-height plank flooring.',
    blockType: BlockType.WOOD_SLAB,
    fuelBurnTime: 8,
    baseValue: 1,
  },
  stone_stairs: {
    id: 'stone_stairs',
    name: 'Masonry Steps',
    category: 'block',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#7a8085',
    description: 'Hewn stone stairs.',
    blockType: BlockType.STONE_STAIRS,
    baseValue: 2,
  },
  stone_slab: {
    id: 'stone_slab',
    name: 'Masonry Slab',
    category: 'block',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#7a8085',
    description: 'Flat stone slab.',
    blockType: BlockType.STONE_SLAB,
    baseValue: 1,
  },
  wood_fence: {
    id: 'wood_fence',
    name: 'Timber Barrier Fence',
    category: 'block',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#946b42',
    description: 'Perimeter fence to secure livestock and villages.',
    blockType: BlockType.FENCE_WOOD,
    fuelBurnTime: 10,
    baseValue: 2,
  },
  copper_block: {
    id: 'copper_block',
    name: 'Solid Bronze Alloy Block',
    category: 'block',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#d98457',
    description: 'Compressed bronze block for storage and heavy structures.',
    blockType: BlockType.COPPER_BLOCK,
    baseValue: 70,
  },
  iron_block: {
    id: 'iron_block',
    name: 'Forged Ferrite Block',
    category: 'block',
    rarity: 'uncommon',
    maxStack: 64,
    iconColor: '#d1d6dc',
    description: 'Heavy structural iron block.',
    blockType: BlockType.IRON_BLOCK,
    baseValue: 140,
  },
  gold_block: {
    id: 'gold_block',
    name: 'Ingot Aurum Block',
    category: 'block',
    rarity: 'rare',
    maxStack: 64,
    iconColor: '#f2d138',
    description: 'Shining gold block of monumental wealth.',
    blockType: BlockType.GOLD_BLOCK,
    baseValue: 300,
  },
  mythril_block: {
    id: 'mythril_block',
    name: 'Refined Mythril Monolith',
    category: 'block',
    rarity: 'epic',
    maxStack: 64,
    iconColor: '#59b3f2',
    description: 'Glowing astral alloy block.',
    blockType: BlockType.MYTHRIL_BLOCK,
    baseValue: 700,
  },

  // ==========================================
  // 7. ARTIFACT ACCESSORIES & RELICS
  // ==========================================
  solar_compass: {
    id: 'solar_compass',
    name: 'Solar Ley Compass',
    category: 'accessory',
    armorSlot: 'accessory',
    rarity: 'epic',
    maxStack: 1,
    iconColor: '#f59e0b',
    description: 'Relic: Ancient astrolabe compass attuning to celestial ley currents.',
    armorValue: 14,
    baseValue: 480,
  },
  berserker_fang: {
    id: 'berserker_fang',
    name: 'Primeval Berserker Fang',
    category: 'accessory',
    armorSlot: 'accessory',
    rarity: 'epic',
    maxStack: 1,
    iconColor: '#ef4444',
    description: 'Relic: Savage trophy pulsing with aggressive fury and critical poise.',
    armorValue: 10,
    baseValue: 520,
  },
  heart_of_colossus: {
    id: 'heart_of_colossus',
    name: 'Ancient Colossus Core',
    category: 'accessory',
    armorSlot: 'accessory',
    rarity: 'legendary',
    maxStack: 1,
    iconColor: '#6366f1',
    description: 'Relic: Heavy mechanical heart of the Ruin Sentinel granting impenetrable poise.',
    armorValue: 30,
    baseValue: 900,
  },

  // ==========================================
  // 8. WORLD MATERIALS, BOTANICALS & GEMS
  // ==========================================
  diamond: {
    id: 'diamond',
    name: 'Star-Faceted Diamond',
    category: 'material',
    rarity: 'rare',
    maxStack: 64,
    iconColor: '#67e8f9',
    description: 'Ultra-hard crystalline gem mined from deep abyss veins.',
    baseValue: 120,
  },
  sun_orchid: {
    id: 'sun_orchid',
    name: 'Radiant Sun Orchid',
    category: 'material',
    rarity: 'uncommon',
    maxStack: 64,
    iconColor: '#fbbf24',
    description: 'Luminous highland flora glowing with solar energy.',
    baseValue: 15,
  },
  lume_mushroom: {
    id: 'lume_mushroom',
    name: 'Luminescent Cave Mushroom',
    category: 'material',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#34d399',
    description: 'Bioluminescent fungus growing in dark caverns.',
    baseValue: 6,
  },
  sapling_oak: {
    id: 'sapling_oak',
    name: 'Oak Tree Sapling',
    category: 'seed',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#4ade80',
    description: 'Plant on fertile soil to grow an oak tree.',
    baseValue: 2,
  },
  sapling_pine: {
    id: 'sapling_pine',
    name: 'Pine Tree Sapling',
    category: 'seed',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#15803d',
    description: 'Plant on fertile soil to grow a highland pine.',
    baseValue: 2,
  },
  glow_dust: {
    id: 'glow_dust',
    name: 'Luminous Glow Dust',
    category: 'material',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#fef08a',
    description: 'Phosphorescent dust harvested from aether crystals and glowing plants.',
    baseValue: 8,
  },
  seeds: {
    id: 'seeds',
    name: 'Wild Grass Seeds',
    category: 'seed',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#86efac',
    description: 'Wild seeds gathered from tall meadow grass.',
    baseValue: 1,
  },
  blue_flower: {
    id: 'blue_flower',
    name: 'Azure Wildflower',
    category: 'material',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#60a5fa',
    description: 'Decorative wildflower used for dyes and alchemical tinctures.',
    baseValue: 3,
  },
  red_flower: {
    id: 'red_flower',
    name: 'Crimson Wildflower',
    category: 'material',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#f87171',
    description: 'Vibrant red meadow flower used in pigment craft.',
    baseValue: 3,
  },
  snowball: {
    id: 'snowball',
    name: 'Compacted Snowball',
    category: 'material',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#f1f5f9',
    description: 'Chilled projectile gathered from arctic snowdrifts.',
    baseValue: 1,
  },
  ice_shard: {
    id: 'ice_shard',
    name: 'Glacial Ice Shard',
    category: 'material',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#a5f3fc',
    description: 'Hardened glacial crystal that cools surrounding heat.',
    baseValue: 4,
  },
  obsidian: {
    id: 'obsidian',
    name: 'Volcanic Obsidian',
    category: 'block',
    rarity: 'rare',
    maxStack: 64,
    iconColor: '#1e1b4b',
    description: 'Blast-resistant volcanic glass formed when water cools lava.',
    blockType: BlockType.OBSIDIAN,
    baseValue: 25,
  },
  basalt: {
    id: 'basalt',
    name: 'Basalt Column Block',
    category: 'block',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#334155',
    description: 'Dense volcanic masonry block from geothermal badlands.',
    blockType: BlockType.BASALT,
    baseValue: 4,
  },
  magma_rock: {
    id: 'magma_rock',
    name: 'Molten Magma Rock',
    category: 'block',
    rarity: 'uncommon',
    maxStack: 64,
    iconColor: '#ea580c',
    description: 'Sizzling volcanic stone radiating intense thermal heat.',
    blockType: BlockType.MAGMA_ROCK,
    baseValue: 10,
  },
  ancient_glyph: {
    id: 'ancient_glyph',
    name: 'Ancient Inscribed Glyph',
    category: 'material',
    rarity: 'rare',
    maxStack: 64,
    iconColor: '#38bdf8',
    description: 'Runic stone tablet carved by the Precursor architects.',
    baseValue: 45,
  },
  wooden_door: {
    id: 'wooden_door',
    name: 'Crafted Timber Door',
    category: 'block',
    rarity: 'common',
    maxStack: 16,
    iconColor: '#a16207',
    description: 'Hinged wooden entryway door.',
    blockType: BlockType.DOOR_BOTTOM,
    baseValue: 6,
  },
  moss_stone: {
    id: 'moss_stone',
    name: 'Overgrown Moss Stone',
    category: 'block',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#4d7c0f',
    description: 'Ancient stone covered in damp verdant moss.',
    blockType: BlockType.MOSS_STONE,
    baseValue: 3,
  },
  coral_shard: {
    id: 'coral_shard',
    name: 'Aetherial Coral Shard',
    category: 'material',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#f43f5e',
    description: 'Vibrant marine coral fragment with mild luminescent properties.',
    baseValue: 5,
  },
  void_eye: {
    id: 'void_eye',
    name: 'Abyssal Void Eye',
    category: 'material',
    rarity: 'legendary',
    maxStack: 16,
    iconColor: '#7e22ce',
    description: 'Unblinking cosmic organ harvested from the Void Sovereign.',
    baseValue: 350,
  },
  obsidian_core: {
    id: 'obsidian_core',
    name: 'Imbued Obsidian Core',
    category: 'material',
    rarity: 'epic',
    maxStack: 16,
    iconColor: '#4338ca',
    description: 'Superheated crystalline core vibrating with seismic power.',
    baseValue: 180,
  },

  // ==========================================
  // 9. MASTERWORK ARTIFACT-UNLOCKED GEAR
  // ==========================================
  aether_lantern: {
    id: 'aether_lantern',
    name: 'Resonant Aether Lantern',
    category: 'block',
    rarity: 'epic',
    maxStack: 16,
    iconColor: '#38bdf8',
    description: 'Masterwork lamp powered by aether prism crystals that dispels void corruption.',
    blockType: BlockType.LANTERN,
    baseValue: 160,
  },
  leyline_compass: {
    id: 'leyline_compass',
    name: 'Leyline Astrolabe Compass',
    category: 'accessory',
    armorSlot: 'accessory',
    rarity: 'epic',
    maxStack: 1,
    iconColor: '#3b82f6',
    description: 'Precision navigational astrolabe that tracks subterranean monoliths and ores.',
    armorValue: 12,
    baseValue: 240,
  },
  kinetic_boots: {
    id: 'kinetic_boots',
    name: 'Kinetic Sprinter Sabatons',
    category: 'armor',
    armorSlot: 'feet',
    rarity: 'epic',
    maxStack: 1,
    iconColor: '#eab308',
    description: 'Chrono-charged boots granting swift momentum and spring leaps.',
    armorValue: 16,
    durability: 800,
    repairMaterial: 'ancient_alloy',
    baseValue: 320,
  },
  recharging_talisman: {
    id: 'recharging_talisman',
    name: 'Chrono Recharging Talisman',
    category: 'accessory',
    armorSlot: 'accessory',
    rarity: 'epic',
    maxStack: 1,
    iconColor: '#f59e0b',
    description: 'Accelerates stamina regeneration and halves ability cooldowns.',
    armorValue: 8,
    baseValue: 280,
  },
  magma_furnace: {
    id: 'magma_furnace',
    name: 'Pyroclast Magma Forge',
    category: 'block',
    rarity: 'epic',
    maxStack: 16,
    iconColor: '#f97316',
    description: 'Geothermal smelter operating at double speed without consuming fuel.',
    blockType: BlockType.FURNACE,
    baseValue: 350,
  },
  pyroclast_blade: {
    id: 'pyroclast_blade',
    name: 'Pyroclast Inferno Blade',
    category: 'weapon',
    rarity: 'epic',
    maxStack: 1,
    iconColor: '#ea580c',
    description: 'Volcanic broadsword igniting struck foes and delivering massive poise damage.',
    attackDamage: 38,
    attackSpeed: 1.4,
    durability: 1200,
    repairMaterial: 'obsidian_core',
    baseValue: 420,
  },
  diver_mask: {
    id: 'diver_mask',
    name: 'Abyssal Siren Diving Mask',
    category: 'armor',
    armorSlot: 'head',
    rarity: 'epic',
    maxStack: 1,
    iconColor: '#06b6d4',
    description: 'Enchanted mask granting infinite aquatic respiration and crystal-clear underwater vision.',
    armorValue: 18,
    durability: 700,
    repairMaterial: 'ancient_alloy',
    baseValue: 360,
  },
  aquatic_spear: {
    id: 'aquatic_spear',
    name: 'Tidal Harpoon Spear',
    category: 'weapon',
    rarity: 'epic',
    maxStack: 1,
    iconColor: '#0ea5e9',
    description: 'Piercing trident dealing extra damage against aquatic and armored beasts.',
    attackDamage: 34,
    attackSpeed: 1.7,
    durability: 950,
    repairMaterial: 'ancient_alloy',
    baseValue: 380,
  },
  void_greatsword: {
    id: 'void_greatsword',
    name: 'Void Sovereign Greatsword',
    category: 'weapon',
    rarity: 'legendary',
    maxStack: 1,
    iconColor: '#9333ea',
    description: 'Colossal dark-matter blade dealing catastrophic damage and breaking enemy poise in a single strike.',
    attackDamage: 55,
    attackSpeed: 1.1,
    durability: 2000,
    repairMaterial: 'void_eye',
    baseValue: 800,
  },
  astral_plate_armor: {
    id: 'astral_plate_armor',
    name: 'Astral Infused Plate Armor',
    category: 'armor',
    armorSlot: 'chest',
    rarity: 'legendary',
    maxStack: 1,
    iconColor: '#8b5cf6',
    description: 'Supreme armor forged from void cores and mythril, absorbing 60% of incoming physical damage.',
    armorValue: 55,
    durability: 2200,
    repairMaterial: 'ancient_alloy',
    baseValue: 950,
  },
  dimensional_warp_anchor: {
    id: 'dimensional_warp_anchor',
    name: 'Dimensional Warp Anchor',
    category: 'block',
    rarity: 'ancient',
    maxStack: 4,
    iconColor: '#c084fc',
    description: 'Precursor gateway anchor enabling instantaneous teleportation between bonded beacons.',
    blockType: BlockType.ANCIENT_RUNE_STONE,
    baseValue: 1200,
  },
  astral_pickaxe: {
    id: 'astral_pickaxe',
    name: 'Astral Transmutation Pickaxe',
    category: 'tool',
    rarity: 'epic',
    maxStack: 1,
    iconColor: '#a855f7',
    description: 'Excavates raw ores directly in their smelted, refined state.',
    toolType: 'pickaxe',
    tier: 4,
    miningEfficiency: 14.0,
    attackDamage: 12,
    attackSpeed: 1.3,
    durability: 1800,
    repairMaterial: 'ancient_alloy',
    baseValue: 500,
  },
  astral_battleaxe: {
    id: 'astral_battleaxe',
    name: 'Astral Cleaver Battleaxe',
    category: 'tool',
    rarity: 'epic',
    maxStack: 1,
    iconColor: '#8b5cf6',
    description: 'Devastating heavy battleaxe capable of felling whole ancient trees in one blow.',
    toolType: 'axe',
    tier: 4,
    miningEfficiency: 15.0,
    attackDamage: 28,
    attackSpeed: 0.95,
    durability: 1800,
    repairMaterial: 'ancient_alloy',
    baseValue: 520,
  },
  alchemical_infuser: {
    id: 'alchemical_infuser',
    name: 'Alchemical Infusion Station',
    category: 'block',
    rarity: 'epic',
    maxStack: 16,
    iconColor: '#10b981',
    description: 'Transmutes raw flora, minerals, and mob essence into potent elixirs and permanent stat enhancers.',
    blockType: BlockType.CRAFTING_BENCH,
    baseValue: 400,
  },
  engineers_wrench: {
    id: 'engineers_wrench',
    name: "Engineer's Calibrated Wrench",
    category: 'tool',
    rarity: 'uncommon',
    maxStack: 1,
    iconColor: '#38bdf8',
    description: 'Calibrates, rotates, and inspects Aether engineering machinery and signal conduits.',
    baseValue: 75,
  },
  aether_core: {
    id: 'aether_core',
    name: 'Aether Core (Basic)',
    category: 'block',
    rarity: 'uncommon',
    maxStack: 16,
    iconColor: '#38bdf8',
    description: 'Generates 20 AE/s energy for connected Ley Conduits and machines.',
    blockType: BlockType.AETHER_CORE,
    baseValue: 150,
  },
  aether_core_advanced: {
    id: 'aether_core_advanced',
    name: 'Aether Core (Advanced)',
    category: 'block',
    rarity: 'rare',
    maxStack: 16,
    iconColor: '#c084fc',
    description: 'Generates 50 AE/s high-yield energy for advanced automation networks.',
    blockType: BlockType.AETHER_CORE_ADVANCED,
    baseValue: 400,
  },
  ley_conduit: {
    id: 'ley_conduit',
    name: 'Ley Conduit',
    category: 'block',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#22d3ee',
    description: 'Transmits energy and signals between connected engineering components.',
    blockType: BlockType.LEY_CONDUIT,
    baseValue: 5,
  },
  crystal_sensor: {
    id: 'crystal_sensor',
    name: 'Crystal Sensor',
    category: 'block',
    rarity: 'uncommon',
    maxStack: 16,
    iconColor: '#facc15',
    description: 'Emits signal based on proximity, daylight, weather, or anomaly state.',
    blockType: BlockType.CRYSTAL_SENSOR,
    baseValue: 60,
  },
  logic_rune: {
    id: 'logic_rune',
    name: 'Logic Rune',
    category: 'block',
    rarity: 'uncommon',
    maxStack: 16,
    iconColor: '#60a5fa',
    description: 'Evaluates boolean AND, OR, NOT, or XOR logic gates.',
    blockType: BlockType.LOGIC_RUNE,
    baseValue: 50,
  },
  delay_rune: {
    id: 'delay_rune',
    name: 'Delay Rune',
    category: 'block',
    rarity: 'uncommon',
    maxStack: 16,
    iconColor: '#fb923c',
    description: 'Delays signal propagation by a configurable duration.',
    blockType: BlockType.DELAY_RUNE,
    baseValue: 50,
  },
  pulse_rune: {
    id: 'pulse_rune',
    name: 'Pulse Rune',
    category: 'block',
    rarity: 'uncommon',
    maxStack: 16,
    iconColor: '#f87171',
    description: 'Emits a single-tick signal pulse on rising input edge.',
    blockType: BlockType.PULSE_RUNE,
    baseValue: 55,
  },
  latch_rune: {
    id: 'latch_rune',
    name: 'Latch Rune',
    category: 'block',
    rarity: 'uncommon',
    maxStack: 16,
    iconColor: '#4ade80',
    description: 'Toggles and maintains state on incoming pulse.',
    blockType: BlockType.LATCH_RUNE,
    baseValue: 55,
  },
  aether_actuator: {
    id: 'aether_actuator',
    name: 'Aether Actuator',
    category: 'block',
    rarity: 'uncommon',
    maxStack: 16,
    iconColor: '#fbbf24',
    description: 'Pushes or pulls a line of up to 12 voxel blocks when triggered.',
    blockType: BlockType.AETHER_ACTUATOR,
    baseValue: 120,
  },
  item_funnel: {
    id: 'item_funnel',
    name: 'Item Funnel',
    category: 'block',
    rarity: 'uncommon',
    maxStack: 16,
    iconColor: '#94a3b8',
    description: 'Transfers items between containers or machines with filtering.',
    blockType: BlockType.ITEM_FUNNEL,
    baseValue: 80,
  },
  aether_storage_relay: {
    id: 'aether_storage_relay',
    name: 'Aether Storage Relay',
    category: 'block',
    rarity: 'uncommon',
    maxStack: 16,
    iconColor: '#38bdf8',
    description: 'Interfaces containers into the logistics network.',
    blockType: BlockType.AETHER_STORAGE_RELAY,
    baseValue: 100,
  },
  ley_harvester: {
    id: 'ley_harvester',
    name: 'Ley Harvester',
    category: 'block',
    rarity: 'rare',
    maxStack: 16,
    iconColor: '#4ade80',
    description: 'Automatically senses, harvests, and replants mature crops.',
    blockType: BlockType.LEY_HARVESTER,
    baseValue: 250,
  },
  irrigation_node: {
    id: 'irrigation_node',
    name: 'Irrigation Node',
    category: 'block',
    rarity: 'uncommon',
    maxStack: 16,
    iconColor: '#60a5fa',
    description: 'Hydrates surrounding farmland plots automatically.',
    blockType: BlockType.IRRIGATION_NODE,
    baseValue: 90,
  },
  resonance_fabricator: {
    id: 'resonance_fabricator',
    name: 'Resonance Fabricator',
    category: 'block',
    rarity: 'rare',
    maxStack: 16,
    iconColor: '#e879f9',
    description: 'Automatically crafts selected recipes using input materials.',
    blockType: BlockType.RESONANCE_FABRICATOR,
    baseValue: 350,
  },
  aether_sentinel_turret: {
    id: 'aether_sentinel_turret',
    name: 'Sentinel Turret',
    category: 'block',
    rarity: 'rare',
    maxStack: 16,
    iconColor: '#f87171',
    description: 'Fires high-energy bolts at hostiles entering base perimeter.',
    blockType: BlockType.AETHER_SENTINEL_TURRET,
    baseValue: 450,
  },
  aether_spike: {
    id: 'aether_spike',
    name: 'Aether Spike Trap',
    category: 'block',
    rarity: 'common',
    maxStack: 32,
    iconColor: '#cbd5e1',
    description: 'Retractable floor spikes activated by signal pulse.',
    blockType: BlockType.AETHER_SPIKE,
    baseValue: 30,
  },
  shock_rune: {
    id: 'shock_rune',
    name: 'Shock Rune Trap',
    category: 'block',
    rarity: 'uncommon',
    maxStack: 32,
    iconColor: '#38bdf8',
    description: 'Discharges electrical shock damage to hostile mobs overhead.',
    blockType: BlockType.SHOCK_RUNE,
    baseValue: 40,
  },
  flame_vent: {
    id: 'flame_vent',
    name: 'Flame Vent Trap',
    category: 'block',
    rarity: 'uncommon',
    maxStack: 32,
    iconColor: '#f97316',
    description: 'Erupts intense flame bursts on signal trigger.',
    blockType: BlockType.FLAME_VENT,
    baseValue: 50,
  },
  aether_lamp: {
    id: 'aether_lamp',
    name: 'Aether Lamp',
    category: 'block',
    rarity: 'common',
    maxStack: 32,
    iconColor: '#fef08a',
    description: 'High-intensity illuminating lamp toggled via signal.',
    blockType: BlockType.AETHER_LAMP,
    baseValue: 25,
  },
  aether_rail: {
    id: 'aether_rail',
    name: 'Aether Rail Track',
    category: 'block',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#94a3b8',
    description: 'Magnetic rail track for passenger and cargo transport.',
    blockType: BlockType.AETHER_RAIL,
    baseValue: 15,
  },
  aether_rail_switch: {
    id: 'aether_rail_switch',
    name: 'Aether Rail Switch',
    category: 'block',
    rarity: 'uncommon',
    maxStack: 32,
    iconColor: '#d97706',
    description: 'Rail track junction switch controlled by signal input.',
    blockType: BlockType.AETHER_RAIL_SWITCH,
    baseValue: 35,
  },
  aether_cargo_cart: {
    id: 'aether_cargo_cart',
    name: 'Aether Cargo Cart',
    category: 'tool',
    rarity: 'uncommon',
    maxStack: 4,
    iconColor: '#f59e0b',
    description: 'Automated rail cart equipped with 18 inventory slots.',
    baseValue: 120,
  },
  ley_generator: {
    id: 'ley_generator',
    name: 'Ley Resonance Generator',
    category: 'block',
    rarity: 'epic',
    maxStack: 8,
    iconColor: '#34d399',
    description: 'Harnesses natural Ley line resonances for clean, endless power.',
    blockType: BlockType.LEY_GENERATOR,
    baseValue: 800,
  },
  blueprint_sheet: {
    id: 'blueprint_sheet',
    name: 'Engineering Blueprint Sheet',
    category: 'material',
    rarity: 'uncommon',
    maxStack: 16,
    iconColor: '#60a5fa',
    description: 'Stores structure schematics for automated assembly.',
    baseValue: 50,
  },

  // ==========================================
  // ECOSYSTEM 2.0 & FISHING ITEMS
  // ==========================================
  fishing_rod: {
    id: 'fishing_rod',
    name: 'Crafted Fishing Rod',
    category: 'tool',
    rarity: 'common',
    maxStack: 1,
    iconColor: '#b45309',
    description: 'A sturdy fishing rod crafted from timber and flexible line. Cast into lakes or oceans.',
    toolType: 'tool' as any,
    durability: 50,
    baseValue: 15,
  },
  aether_rod: {
    id: 'aether_rod',
    name: 'Aether Resonance Rod',
    category: 'tool',
    rarity: 'rare',
    maxStack: 1,
    iconColor: '#38bdf8',
    description: 'Crystal-reinforced fishing rod that attracts rare bioluminescent aquatic creatures.',
    toolType: 'tool' as any,
    durability: 150,
    baseValue: 120,
  },
  earth_worm: {
    id: 'earth_worm',
    name: 'Earth Worm Bait',
    category: 'material',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#a16207',
    description: 'Wiggling soil worm. Increases fishing bite speed in fresh waters.',
    baseValue: 2,
  },
  aether_bait: {
    id: 'aether_bait',
    name: 'Luminescent Aether Bait',
    category: 'material',
    rarity: 'uncommon',
    maxStack: 64,
    iconColor: '#818cf8',
    description: 'Infused bait that entices rare Aetheric and abyssal fish species.',
    baseValue: 15,
  },
  river_trout: {
    id: 'river_trout',
    name: 'River Trout',
    category: 'food',
    rarity: 'common',
    maxStack: 32,
    iconColor: '#38bdf8',
    description: 'Freshwater fish caught from rivers and lakes.',
    foodValue: 12,
    saturationValue: 8,
    baseValue: 6,
  },
  sun_bass: {
    id: 'sun_bass',
    name: 'Sunswept Bass',
    category: 'food',
    rarity: 'common',
    maxStack: 32,
    iconColor: '#facc15',
    description: 'Golden bass found in warm coastal and meadow waters.',
    foodValue: 14,
    saturationValue: 10,
    baseValue: 8,
  },
  silver_salmon: {
    id: 'silver_salmon',
    name: 'Silver Salmon',
    category: 'food',
    rarity: 'uncommon',
    maxStack: 32,
    iconColor: '#cbd5e1',
    description: 'Nutritious salmon that restores stamina and hunger.',
    foodValue: 20,
    saturationValue: 16,
    staminaRestore: 25,
    baseValue: 18,
  },
  aether_glowfin: {
    id: 'aether_glowfin',
    name: 'Azure Glowfin',
    category: 'food',
    rarity: 'rare',
    maxStack: 16,
    iconColor: '#0284c7',
    description: 'Radiant crystal fish. Restores health and provides slight Aether resistance.',
    foodValue: 28,
    saturationValue: 24,
    healValue: 20,
    baseValue: 50,
  },
  aether_fish_stew: {
    id: 'aether_fish_stew',
    name: 'Aether Fish Chowder',
    category: 'food',
    rarity: 'rare',
    maxStack: 16,
    iconColor: '#0ea5e9',
    description: 'Hearty chowder cooked with Aether Glowfin and crops. Boosts max health temporarily.',
    foodValue: 40,
    saturationValue: 35,
    healValue: 30,
    staminaRestore: 40,
    baseValue: 80,
  },
  woolbeast_fiber: {
    id: 'woolbeast_fiber',
    name: 'Woolbeast Fiber',
    category: 'material',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#f8fafc',
    description: 'Soft insulating fleece gathered from domestic Woolbeasts.',
    baseValue: 5,
  },
  milk_bucket: {
    id: 'milk_bucket',
    name: 'Grazeback Milk Pail',
    category: 'food',
    rarity: 'common',
    maxStack: 16,
    iconColor: '#f1f5f9',
    description: 'Fresh milk pail from Grazebacks. Clears debuffs and restores stamina.',
    foodValue: 15,
    staminaRestore: 30,
    baseValue: 10,
  },
  glow_egg: {
    id: 'glow_egg',
    name: 'Bioluminescent Glow-Egg',
    category: 'material',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#fef08a',
    description: 'Glowing egg laid by Glowhens. Used in cooking and alchemy.',
    foodValue: 10,
    baseValue: 8,
  },
  aether_wax: {
    id: 'aether_wax',
    name: 'Crystal Bee Wax',
    category: 'material',
    rarity: 'uncommon',
    maxStack: 64,
    iconColor: '#f59e0b',
    description: 'Viscous crystal wax secreted by Astral Bees. Essential for advanced engineering and insulation.',
    baseValue: 25,
  },
  fertilizer: {
    id: 'fertilizer',
    name: 'Rich Bio-Fertilizer',
    category: 'material',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#65a30d',
    description: 'Nutrient-rich soil conditioner produced from livestock. Instantly advances crop growth stages.',
    baseValue: 6,
  },
  animal_feed: {
    id: 'animal_feed',
    name: 'Enriched Grain Feed',
    category: 'material',
    rarity: 'common',
    maxStack: 64,
    iconColor: '#eab308',
    description: 'Nutritious feed blend of wheat and seeds used to tame and breed domestic livestock.',
    baseValue: 4,
  },
};

