// Creature Registry & Data-Driven Fauna Definitions for VoxelVerse Living World 2.0
import { ItemRarity } from '../../types';

export type CreatureRole = 'PREY' | 'PREDATOR' | 'OMNIVORE' | 'SCAVENGER' | 'PASSIVE' | 'DOMESTIC' | 'AETHER_CREATURE';
export type DietType = 'HERBIVORE' | 'CARNIVORE' | 'OMNIVORE' | 'AETHER_FEEDER';
export type ActivityCycle = 'diurnal' | 'nocturnal' | 'crepuscular' | 'all_day';

export interface CreatureProductDef {
  itemId: string;
  count: number;
  intervalSeconds: number;
  requiresFood?: boolean;
}

export interface CreatureDropDef {
  itemId: string;
  chance: number;
  count: [number, number];
}

export interface CreatureDef {
  id: string;
  name: string;
  role: CreatureRole;
  biomes: string[];
  activity: ActivityCycle;
  diet: DietType;
  groupSize: [number, number]; // [min, max]
  fearRadius: number; // distance at which prey flees
  predatorTargets?: string[]; // IDs of prey this creature hunts
  tameable: boolean;
  preferredFood?: string[]; // items used to gain trust / tame
  mountCapable?: boolean;
  mountSpeedBonus?: number;
  mountJumpBonus?: number;
  breedable: boolean;
  breedingFood?: string[];
  productOutput?: CreatureProductDef;
  drops: CreatureDropDef[];
  rarity: 'common' | 'uncommon' | 'rare' | 'aetheric';
  modelType: string;
  baseHealth: number;
  baseSpeed: number;
  baseDamage: number;
  description: string;
  culturalRegion?: string;
  stabilityTrigger?: 'high' | 'low' | 'anomaly' | 'any';
  cleansingItem?: string;
  cleansingRewardArtifact?: string;
  isMythic?: boolean;
  isBoss?: boolean;
  lore?: string;
}

export const CREATURE_REGISTRY: Record<string, CreatureDef> = {
  // 1. Aether Stag (Aether Mount Fauna)
  aether_stag: {
    id: 'aether_stag',
    name: 'Aurelion Crystal Stag',
    role: 'AETHER_CREATURE',
    biomes: ['plains', 'meadow', 'crystal_spires'],
    activity: 'all_day',
    diet: 'AETHER_FEEDER',
    groupSize: [2, 5],
    fearRadius: 8,
    tameable: true,
    preferredFood: ['aether_crystal', 'golden_fruit'],
    mountCapable: true,
    mountSpeedBonus: 1.45,
    mountJumpBonus: 1.6,
    breedable: true,
    breedingFood: ['aether_crystal'],
    drops: [
      { itemId: 'cooked_meat', chance: 1.0, count: [1, 2] },
      { itemId: 'aether_crystal', chance: 0.45, count: [1, 2] },
    ],
    rarity: 'uncommon',
    modelType: 'stag',
    baseHealth: 40,
    baseSpeed: 2.8,
    baseDamage: 0,
    description: 'A majestic stag crowned with glowing cyan crystal antlers that channel ley energy.',
  },

  // 2. Woolbeast (Domestic Wool/Fiber Livestock)
  woolbeast: {
    id: 'woolbeast',
    name: 'Boreal Woolbeast',
    role: 'DOMESTIC',
    biomes: ['plains', 'taiga', 'snow_forest', 'meadow'],
    activity: 'diurnal',
    diet: 'HERBIVORE',
    groupSize: [3, 6],
    fearRadius: 6,
    tameable: true,
    preferredFood: ['wheat', 'seeds'],
    breedable: true,
    breedingFood: ['wheat'],
    productOutput: {
      itemId: 'woolbeast_fiber',
      count: 2,
      intervalSeconds: 120,
      requiresFood: true,
    },
    drops: [
      { itemId: 'woolbeast_fiber', chance: 1.0, count: [2, 4] },
      { itemId: 'cooked_meat', chance: 0.8, count: [1, 2] },
    ],
    rarity: 'common',
    modelType: 'woolbeast',
    baseHealth: 35,
    baseSpeed: 1.8,
    baseDamage: 0,
    description: 'A fluffy quadrupeds that grazes peaceful fields, yielding thick, warmth-insulating fiber.',
  },

  // 3. Grazeback (Heavy Livestock & Milk Producer)
  grazeback: {
    id: 'grazeback',
    name: 'Ironhide Grazeback',
    role: 'DOMESTIC',
    biomes: ['plains', 'mountain', 'savanna'],
    activity: 'diurnal',
    diet: 'HERBIVORE',
    groupSize: [2, 4],
    fearRadius: 5,
    tameable: true,
    preferredFood: ['carrot', 'potato', 'wheat'],
    breedable: true,
    breedingFood: ['carrot'],
    productOutput: {
      itemId: 'milk_bucket',
      count: 1,
      intervalSeconds: 150,
      requiresFood: true,
    },
    drops: [
      { itemId: 'raw_meat', chance: 1.0, count: [2, 3] },
      { itemId: 'leather', chance: 0.6, count: [1, 2] },
    ],
    rarity: 'common',
    modelType: 'grazeback',
    baseHealth: 50,
    baseSpeed: 1.5,
    baseDamage: 4,
    description: 'A sturdy, armored grazer that supplies nourishing milk and rich hides to homesteaders.',
  },

  // 4. Shadow Wolf (Predator Pack Hunter)
  shadow_wolf: {
    id: 'shadow_wolf',
    name: 'Shadow Wolf',
    role: 'PREDATOR',
    biomes: ['forest', 'dense_forest', 'taiga', 'snow_forest'],
    activity: 'crepuscular',
    diet: 'CARNIVORE',
    groupSize: [2, 4],
    fearRadius: 0,
    predatorTargets: ['woolbeast', 'grazeback', 'glowhen', 'aether_stag'],
    tameable: true,
    preferredFood: ['raw_meat', 'cooked_meat'],
    breedable: true,
    breedingFood: ['cooked_meat'],
    drops: [
      { itemId: 'raw_meat', chance: 0.9, count: [1, 2] },
      { itemId: 'coal', chance: 0.5, count: [1, 2] },
    ],
    rarity: 'common',
    modelType: 'wolf',
    baseHealth: 45,
    baseSpeed: 3.6,
    baseDamage: 12,
    description: 'A dark predatory wolf that stalks in packs during twilight and night hours.',
  },

  // 5. Glowhen (Poultry Livestock & Egg Producer)
  glowhen: {
    id: 'glowhen',
    name: 'Luminescent Glowhen',
    role: 'DOMESTIC',
    biomes: ['forest', 'jungle', 'plains'],
    activity: 'diurnal',
    diet: 'HERBIVORE',
    groupSize: [3, 7],
    fearRadius: 7,
    tameable: true,
    preferredFood: ['seeds', 'wheat'],
    breedable: true,
    breedingFood: ['seeds'],
    productOutput: {
      itemId: 'glow_egg',
      count: 1,
      intervalSeconds: 90,
      requiresFood: true,
    },
    drops: [
      { itemId: 'cooked_meat', chance: 0.8, count: [1, 1] },
      { itemId: 'glow_egg', chance: 0.5, count: [1, 1] },
    ],
    rarity: 'common',
    modelType: 'glowhen',
    baseHealth: 15,
    baseSpeed: 2.2,
    baseDamage: 0,
    description: 'A vibrant feathered fowl whose tail feathers emit a soft warm bioluminescent glow.',
  },

  // 6. Crystal Bee (Aether Pollinator Insect)
  crystal_bee: {
    id: 'crystal_bee',
    name: 'Astral Crystal Bee',
    role: 'AETHER_CREATURE',
    biomes: ['meadow', 'crystal_spires', 'forest'],
    activity: 'diurnal',
    diet: 'AETHER_FEEDER',
    groupSize: [2, 5],
    fearRadius: 4,
    tameable: false,
    breedable: false,
    productOutput: {
      itemId: 'aether_wax',
      count: 1,
      intervalSeconds: 180,
    },
    drops: [
      { itemId: 'aether_wax', chance: 0.9, count: [1, 2] },
    ],
    rarity: 'uncommon',
    modelType: 'bee',
    baseHealth: 10,
    baseSpeed: 2.5,
    baseDamage: 2,
    description: 'A glowing Aether insect that pollinates flowers and significantly accelerates nearby crop growth.',
  },

  // 7. Glowfin (Aquatic Water Life)
  glowfin: {
    id: 'glowfin',
    name: 'Azure Glowfin',
    role: 'PASSIVE',
    biomes: ['ocean', 'deep_ocean', 'swamp', 'crystal_spires'],
    activity: 'all_day',
    diet: 'HERBIVORE',
    groupSize: [3, 8],
    fearRadius: 5,
    tameable: false,
    breedable: false,
    drops: [
      { itemId: 'aether_glowfin', chance: 1.0, count: [1, 1] },
    ],
    rarity: 'common',
    modelType: 'glowfin',
    baseHealth: 10,
    baseSpeed: 2.0,
    baseDamage: 0,
    description: 'An elegant aquatic creature with luminous blue fins swimming in pristine waters.',
  },

  // 8. Void Lynx (Rare Aether Predator)
  void_lynx: {
    id: 'void_lynx',
    name: 'Void Lynx',
    role: 'PREDATOR',
    biomes: ['corrupted_barrens', 'abyssal_chasm', 'volcanic'],
    activity: 'nocturnal',
    diet: 'CARNIVORE',
    groupSize: [1, 2],
    fearRadius: 0,
    predatorTargets: ['aether_stag', 'woolbeast', 'grazeback', 'shadow_wolf'],
    tameable: true,
    preferredFood: ['ancient_glyph', 'raw_iron'],
    mountCapable: false,
    breedable: true,
    breedingFood: ['ancient_glyph'],
    drops: [
      { itemId: 'aether_crystal', chance: 0.8, count: [1, 3] },
      { itemId: 'ancient_glyph', chance: 0.3, count: [1, 1] },
    ],
    rarity: 'rare',
    modelType: 'void_lynx',
    baseHealth: 80,
    baseSpeed: 4.2,
    baseDamage: 18,
    description: 'A elusive, deadly void feline with purple crackling energy around its claws.',
  },

  // =========================================================================
  // VOXELVERSE — NUSANTARA MYTHIC CREATURES EXPANSION 1.0
  // =========================================================================

  // --- PASSIVE / NEUTRAL MYTHIC GUARDIANS (7) ---
  lembu_sekti: {
    id: 'lembu_sekti',
    name: 'Saptamurti Lembu Sekti',
    role: 'AETHER_CREATURE',
    biomes: ['plains', 'meadow', 'volcanic'],
    activity: 'all_day',
    diet: 'AETHER_FEEDER',
    groupSize: [1, 2],
    fearRadius: 0,
    tameable: true,
    preferredFood: ['beras_wangi', 'aether_crystal'],
    mountCapable: true,
    mountSpeedBonus: 1.5,
    mountJumpBonus: 1.2,
    breedable: false,
    drops: [
      { itemId: 'gading_lembu_sekti', chance: 1.0, count: [1, 1] },
      { itemId: 'aether_crystal', chance: 0.8, count: [2, 4] },
    ],
    rarity: 'aetheric',
    modelType: 'lembu_sekti',
    baseHealth: 180,
    baseSpeed: 2.5,
    baseDamage: 8,
    description: 'Celestial ox with golden horns and volcanic relief armor that blesses fertile crops.',
    culturalRegion: 'Jawa',
    stabilityTrigger: 'high',
    cleansingItem: 'beras_wangi',
    cleansingRewardArtifact: 'solaris_aegis',
    isMythic: true,
    lore: 'Legend says Ki Lurah Tejo rode Lembu Sekti across the fiery slopes of Mount Kelud to channel Aether streams into rice fields.',
  },

  singa_marapi: {
    id: 'singa_marapi',
    name: 'Rangkiang Singa Marapi',
    role: 'AETHER_CREATURE',
    biomes: ['highlands', 'mountain', 'snow_forest'],
    activity: 'crepuscular',
    diet: 'AETHER_FEEDER',
    groupSize: [1, 1],
    fearRadius: 0,
    tameable: true,
    preferredFood: ['kopi_gunung', 'gaharu_incense'],
    mountCapable: true,
    mountSpeedBonus: 1.6,
    mountJumpBonus: 1.8,
    breedable: false,
    drops: [
      { itemId: 'tanduk_singa_marapi', chance: 1.0, count: [1, 1] },
      { itemId: 'silver_filigree', chance: 0.9, count: [1, 2] },
    ],
    rarity: 'aetheric',
    modelType: 'singa_marapi',
    baseHealth: 160,
    baseSpeed: 3.2,
    baseDamage: 12,
    description: 'Highland stag-lion with sweeping buffalo-roof horns and woven silver filigree mane.',
    culturalRegion: 'Minang',
    stabilityTrigger: 'high',
    cleansingItem: 'gaharu_incense',
    cleansingRewardArtifact: 'keris_singa_marapi',
    isMythic: true,
    lore: 'Sentinel of Luhak Nan Tigo. Its silver mane glows whenever rain dances across Singgalang and Marapi peaks.',
  },

  enggang_celestial: {
    id: 'enggang_celestial',
    name: 'Enggang Gading Celestial',
    role: 'PASSIVE',
    biomes: ['jungle', 'swamp', 'forest'],
    activity: 'diurnal',
    diet: 'AETHER_FEEDER',
    groupSize: [1, 2],
    fearRadius: 6,
    tameable: false,
    breedable: false,
    drops: [
      { itemId: 'bulu_enggang_celestial', chance: 1.0, count: [2, 4] },
      { itemId: 'damar_resin', chance: 0.8, count: [2, 3] },
    ],
    rarity: 'aetheric',
    modelType: 'enggang_celestial',
    baseHealth: 120,
    baseSpeed: 3.8,
    baseDamage: 0,
    description: 'Sacred hornbill bird with ivory casque horn and geometric feathered wings.',
    culturalRegion: 'Borneo',
    stabilityTrigger: 'high',
    cleansingItem: 'damar_resin',
    cleansingRewardArtifact: 'solar_compass',
    isMythic: true,
    lore: 'Revered messenger of the upper skies in Huma Betang. Its wings leave trails of golden Ley sparks over Ulin treetops.',
  },

  barong_aether: {
    id: 'barong_aether',
    name: 'Barong Keket Aether Guardian',
    role: 'AETHER_CREATURE',
    biomes: ['meadow', 'plains', 'forest'],
    activity: 'all_day',
    diet: 'AETHER_FEEDER',
    groupSize: [1, 1],
    fearRadius: 0,
    tameable: true,
    preferredFood: ['dupa_sesaji', 'aether_crystal'],
    mountCapable: false,
    breedable: false,
    drops: [
      { itemId: 'mata_barong_aether', chance: 1.0, count: [1, 1] },
      { itemId: 'paras_stone_carving', chance: 0.9, count: [1, 3] },
    ],
    rarity: 'aetheric',
    modelType: 'barong_aether',
    baseHealth: 220,
    baseSpeed: 2.8,
    baseDamage: 15,
    description: 'Feline-dragon guardian deity with ornate golden carved mask, mirror chest medallion, and floral garlands.',
    culturalRegion: 'Bali',
    stabilityTrigger: 'high',
    cleansingItem: 'dupa_sesaji',
    cleansingRewardArtifact: 'mahktota_barong_aether',
    isMythic: true,
    lore: 'Embodiment of cosmic virtue and Dharma. When Barong dances near Subak shrines, shadow corruptions wither into dust.',
  },

  tedong_bonga: {
    id: 'tedong_bonga',
    name: 'Tedong Bonga Astral Bull',
    role: 'PASSIVE',
    biomes: ['highlands', 'mountain', 'savanna'],
    activity: 'diurnal',
    diet: 'HERBIVORE',
    groupSize: [1, 3],
    fearRadius: 4,
    tameable: true,
    preferredFood: ['toraja_arabica', 'wheat'],
    mountCapable: true,
    mountSpeedBonus: 1.35,
    mountJumpBonus: 1.3,
    breedable: false,
    drops: [
      { itemId: 'tanduk_tedong_bonga', chance: 1.0, count: [1, 1] },
      { itemId: 'ijuk_thatch', chance: 0.8, count: [3, 5] },
    ],
    rarity: 'rare',
    modelType: 'tedong_bonga',
    baseHealth: 150,
    baseSpeed: 2.2,
    baseDamage: 10,
    description: 'Sacred piebald buffalo with wide sweeping horns carved with Pa\'ssura geometric motifs.',
    culturalRegion: 'Toraja',
    stabilityTrigger: 'high',
    cleansingItem: 'toraja_arabica',
    cleansingRewardArtifact: 'eye_of_aether',
    isMythic: true,
    lore: 'The holy star-marked bull that guides ancestral souls across karst cliffs to Puya.',
  },

  cenderawasih_astral: {
    id: 'cenderawasih_astral',
    name: 'Cenderawasih Astral Bird',
    role: 'PASSIVE',
    biomes: ['jungle', 'mountain', 'crystal_spires'],
    activity: 'diurnal',
    diet: 'AETHER_FEEDER',
    groupSize: [1, 2],
    fearRadius: 5,
    tameable: false,
    breedable: false,
    drops: [
      { itemId: 'bulu_cenderawasih', chance: 1.0, count: [1, 3] },
      { itemId: 'noken_woven', chance: 0.7, count: [1, 1] },
    ],
    rarity: 'aetheric',
    modelType: 'cenderawasih_astral',
    baseHealth: 100,
    baseSpeed: 4.0,
    baseDamage: 0,
    description: 'Celestial paradise bird with shimmering golden tail plumes trailing luminescent Ley dust.',
    culturalRegion: 'Papua',
    stabilityTrigger: 'high',
    cleansingItem: 'sago_flour',
    cleansingRewardArtifact: 'chrono_core',
    isMythic: true,
    lore: 'Known as the Bird of Heaven in Baliem Valley. Observing its flight grants speed and wind agility.',
  },

  penyu_garam: {
    id: 'penyu_garam',
    name: 'Samudra Salt Reef Turtle',
    role: 'PASSIVE',
    biomes: ['ocean', 'deep_ocean', 'beach'],
    activity: 'all_day',
    diet: 'HERBIVORE',
    groupSize: [1, 1],
    fearRadius: 0,
    tameable: true,
    preferredFood: ['solar_sea_salt', 'seaweed'],
    mountCapable: true,
    mountSpeedBonus: 1.7,
    mountJumpBonus: 0.5,
    breedable: false,
    drops: [
      { itemId: 'kristal_garam_samudra', chance: 1.0, count: [2, 5] },
      { itemId: 'solar_sea_salt', chance: 1.0, count: [4, 8] },
    ],
    rarity: 'rare',
    modelType: 'penyu_garam',
    baseHealth: 250,
    baseSpeed: 1.8,
    baseDamage: 0,
    description: 'Colossal sea turtle carrying a miniature salt-crystal reef on its carved shell.',
    culturalRegion: 'Eastern Isles',
    stabilityTrigger: 'high',
    cleansingItem: 'solar_sea_salt',
    cleansingRewardArtifact: 'tidal_pearl',
    isMythic: true,
    lore: 'Voyagers from Banda Islands follow the glowing salt crystals on its shell to navigate marine trenches safely.',
  },

  // --- HOSTILE MYTHIC CREATURES (6) ---
  banaspati_fiend: {
    id: 'banaspati_fiend',
    name: 'Banaspati Blaze Fiend',
    role: 'PREDATOR',
    biomes: ['volcanic', 'corrupted_barrens'],
    activity: 'nocturnal',
    diet: 'AETHER_FEEDER',
    groupSize: [1, 2],
    fearRadius: 0,
    predatorTargets: ['aether_stag', 'woolbeast'],
    tameable: false,
    breedable: false,
    drops: [
      { itemId: 'inti_api_banaspati', chance: 1.0, count: [1, 2] },
      { itemId: 'volcanic_brick', chance: 0.8, count: [2, 4] },
    ],
    rarity: 'rare',
    modelType: 'banaspati_fiend',
    baseHealth: 140,
    baseSpeed: 3.5,
    baseDamage: 18,
    description: 'Hovering fiery elemental orb framed by fiery jaw motifs and volcanic ash crown that hurls magma bursts.',
    culturalRegion: 'Jawa',
    stabilityTrigger: 'low',
    cleansingItem: 'terracotta_pottery',
    cleansingRewardArtifact: 'solaris_aegis',
    isMythic: true,
    lore: 'A wild spirit born from uncalmed geothermal vents. It tumbles upside down through midnight forests setting trees ablaze.',
  },

  harimau_cindaku: {
    id: 'harimau_cindaku',
    name: 'Cindaku Mist Stalker',
    role: 'PREDATOR',
    biomes: ['mountain', 'highlands', 'forest'],
    activity: 'nocturnal',
    diet: 'CARNIVORE',
    groupSize: [1, 1],
    fearRadius: 0,
    predatorTargets: ['aether_stag', 'singa_marapi'],
    tameable: false,
    breedable: false,
    drops: [
      { itemId: 'taring_cindaku', chance: 1.0, count: [1, 1] },
      { itemId: 'kopi_gunung', chance: 0.7, count: [2, 3] },
    ],
    rarity: 'rare',
    modelType: 'harimau_cindaku',
    baseHealth: 170,
    baseSpeed: 4.2,
    baseDamage: 22,
    description: 'Phantom tiger-humanoid predator with glowing cyan eye slits that teleports through mountain fog.',
    culturalRegion: 'Minang',
    stabilityTrigger: 'low',
    cleansingItem: 'rendang_spices',
    cleansingRewardArtifact: 'berserker_fang',
    isMythic: true,
    lore: 'Ancient tiger shapeshifter bound by oath to guard Kerinci peak. When leylines decay, it hunts lost travelers in the fog.',
  },

  buaya_puang: {
    id: 'buaya_puang',
    name: 'Puang Sacred Ulin Maw',
    role: 'PREDATOR',
    biomes: ['swamp', 'river', 'jungle'],
    activity: 'all_day',
    diet: 'CARNIVORE',
    groupSize: [1, 1],
    fearRadius: 0,
    predatorTargets: ['woolbeast', 'aether_stag'],
    tameable: false,
    breedable: false,
    drops: [
      { itemId: 'sisik_ulin_puang', chance: 1.0, count: [1, 2] },
      { itemId: 'ulin_planks', chance: 0.9, count: [2, 4] },
    ],
    rarity: 'rare',
    modelType: 'buaya_puang',
    baseHealth: 210,
    baseSpeed: 2.4,
    baseDamage: 25,
    description: 'Giant crocodilian beast clad in petrified ironwood armor plates with glowing green swamp eyes.',
    culturalRegion: 'Borneo',
    stabilityTrigger: 'low',
    cleansingItem: 'damar_resin',
    cleansingRewardArtifact: 'precursor_matrix',
    isMythic: true,
    lore: 'The white river maw of Kapuas and Mahakam. Its ironwood scales repel arrows and iron blades alike.',
  },

  rangda_corrupted: {
    id: 'rangda_corrupted',
    name: 'Shadow Rangda Spirit',
    role: 'PREDATOR',
    biomes: ['corrupted_barrens', 'forest', 'swamp'],
    activity: 'nocturnal',
    diet: 'AETHER_FEEDER',
    groupSize: [1, 1],
    fearRadius: 0,
    predatorTargets: ['barong_aether', 'aether_stag'],
    tameable: false,
    breedable: false,
    drops: [
      { itemId: 'topeng_rangda_shadow', chance: 1.0, count: [1, 1] },
      { itemId: 'aether_crystal', chance: 0.9, count: [2, 4] },
    ],
    rarity: 'aetheric',
    modelType: 'rangda_corrupted',
    baseHealth: 200,
    baseSpeed: 3.0,
    baseDamage: 24,
    description: 'Floating mask demon with long flame tongue, clawed hands, and corruptive shadow bursts.',
    culturalRegion: 'Bali',
    stabilityTrigger: 'low',
    cleansingItem: 'dupa_sesaji',
    cleansingRewardArtifact: 'void_walker_ring',
    isMythic: true,
    lore: 'Empress of dark Ley energies. When Ley stability collapses, Rangda rises from cemetery gates seeking to undo Barong\'s order.',
  },

  poci_kelep: {
    id: 'poci_kelep',
    name: 'Karst Cliff Stalker Poci',
    role: 'PREDATOR',
    biomes: ['mountain', 'volcanic', 'corrupted_barrens'],
    activity: 'nocturnal',
    diet: 'CARNIVORE',
    groupSize: [1, 2],
    fearRadius: 0,
    predatorTargets: ['tedong_bonga', 'woolbeast'],
    tameable: false,
    breedable: false,
    drops: [
      { itemId: 'batu_poci_karst', chance: 1.0, count: [1, 2] },
      { itemId: 'carved_beam', chance: 0.7, count: [1, 2] },
    ],
    rarity: 'rare',
    modelType: 'poci_kelep',
    baseHealth: 150,
    baseSpeed: 3.6,
    baseDamage: 18,
    description: 'Gargoyle beast sheathed in karst limestone that leaps down from high cliffs upon prey.',
    culturalRegion: 'Toraja',
    stabilityTrigger: 'low',
    cleansingItem: 'toraja_arabica',
    cleansingRewardArtifact: 'eye_of_aether',
    isMythic: true,
    lore: 'Guardians of ancient cliffside burial chambers corrupted by void resonance.',
  },

  asmat_war_phantom: {
    id: 'asmat_war_phantom',
    name: 'Ancestral Shield Phantom',
    role: 'PREDATOR',
    biomes: ['jungle', 'swamp', 'corrupted_barrens'],
    activity: 'nocturnal',
    diet: 'AETHER_FEEDER',
    groupSize: [1, 1],
    fearRadius: 0,
    predatorTargets: ['aether_stag', 'cenderawasih_astral'],
    tameable: false,
    breedable: false,
    drops: [
      { itemId: 'perisai_asmat_pusaka', chance: 1.0, count: [1, 1] },
      { itemId: 'noken_woven', chance: 0.8, count: [1, 2] },
    ],
    rarity: 'rare',
    modelType: 'asmat_war_phantom',
    baseHealth: 180,
    baseSpeed: 2.8,
    baseDamage: 20,
    description: 'Phantom warrior bearing a giant carved ancestral shield that reflects frontal damage.',
    culturalRegion: 'Papua',
    stabilityTrigger: 'low',
    cleansingItem: 'noken_woven',
    cleansingRewardArtifact: 'perisai_asmat_pusaka',
    isMythic: true,
    lore: 'A spectral warrior spirit carved into wood and animated by ancestral Ley echoes.',
  },

  // --- RARE ENCOUNTERS (2) ---
  rimba_pari: {
    id: 'rimba_pari',
    name: 'Sianok Flora Siren',
    role: 'AETHER_CREATURE',
    biomes: ['forest', 'jungle', 'highlands'],
    activity: 'crepuscular',
    diet: 'AETHER_FEEDER',
    groupSize: [1, 1],
    fearRadius: 0,
    tameable: true,
    preferredFood: ['gaharu_incense', 'aether_crystal'],
    mountCapable: false,
    breedable: false,
    drops: [
      { itemId: 'bunga_pari_rimba', chance: 1.0, count: [1, 2] },
      { itemId: 'gaharu_incense', chance: 1.0, count: [2, 3] },
    ],
    rarity: 'aetheric',
    modelType: 'rimba_pari',
    baseHealth: 130,
    baseSpeed: 2.0,
    baseDamage: 0,
    description: 'Serene flower-crowned forest spirit floating near waterfalls offering sacred cleansing rites.',
    culturalRegion: 'Minang',
    stabilityTrigger: 'anomaly',
    cleansingItem: 'gaharu_incense',
    cleansingRewardArtifact: 'chrono_core',
    isMythic: true,
    lore: 'Appears during Aether distortions in lush river gorges. Cleansing her presence purifies nearby land.',
  },

  warak_ngendog: {
    id: 'warak_ngendog',
    name: 'Warak Astral Drake',
    role: 'AETHER_CREATURE',
    biomes: ['plains', 'meadow', 'volcanic'],
    activity: 'all_day',
    diet: 'AETHER_FEEDER',
    groupSize: [1, 1],
    fearRadius: 0,
    tameable: true,
    preferredFood: ['beras_wangi', 'terracotta_tile'],
    mountCapable: true,
    mountSpeedBonus: 1.55,
    mountJumpBonus: 1.5,
    breedable: false,
    drops: [
      { itemId: 'telur_warak_astral', chance: 1.0, count: [1, 1] },
      { itemId: 'aether_crystal', chance: 0.9, count: [3, 5] },
    ],
    rarity: 'aetheric',
    modelType: 'warak_ngendog',
    baseHealth: 190,
    baseSpeed: 3.2,
    baseDamage: 14,
    description: 'Vibrant hybrid mythic creature with dragon head, bovid body, and avian wings.',
    culturalRegion: 'Jawa',
    stabilityTrigger: 'anomaly',
    cleansingItem: 'beras_wangi',
    cleansingRewardArtifact: 'solaris_aegis',
    isMythic: true,
    lore: 'Celebrated symbol of harmony between earth, sky, and sea. Spawns during celestial alignment anomalies.',
  },

  // --- MINIBOSSES (2) ---
  candi_sentinel: {
    id: 'candi_sentinel',
    name: 'Batara Candi Sentinel',
    role: 'PREDATOR',
    biomes: ['volcanic', 'plains', 'crystal_spires'],
    activity: 'all_day',
    diet: 'AETHER_FEEDER',
    groupSize: [1, 1],
    fearRadius: 0,
    tameable: false,
    breedable: false,
    drops: [
      { itemId: 'batu_candi_aether', chance: 1.0, count: [2, 4] },
      { itemId: 'aether_crystal', chance: 1.0, count: [4, 8] },
    ],
    rarity: 'aetheric',
    modelType: 'candi_sentinel',
    baseHealth: 450,
    baseSpeed: 1.8,
    baseDamage: 32,
    description: 'Ancient stone temple colossus adorned with relief carvings and glowing blue Aether eye cores.',
    culturalRegion: 'Jawa',
    stabilityTrigger: 'low',
    cleansingItem: 'kris_pusaka',
    cleansingRewardArtifact: 'precursor_matrix',
    isMythic: true,
    isBoss: true,
    lore: 'Awakened guardian of sunken temple ruins. Performs heavy ground slams that shatter rock formations.',
  },

  raksasa_ulin: {
    id: 'raksasa_ulin',
    name: 'Ulin Forest Ancient Raksasa',
    role: 'PREDATOR',
    biomes: ['jungle', 'swamp', 'forest'],
    activity: 'all_day',
    diet: 'AETHER_FEEDER',
    groupSize: [1, 1],
    fearRadius: 0,
    tameable: false,
    breedable: false,
    drops: [
      { itemId: 'teras_ulin_ancient', chance: 1.0, count: [2, 4] },
      { itemId: 'damar_resin', chance: 1.0, count: [4, 6] },
    ],
    rarity: 'aetheric',
    modelType: 'raksasa_ulin',
    baseHealth: 500,
    baseSpeed: 1.6,
    baseDamage: 35,
    description: 'Massive walking tree titan composed of petrified Ulin ironwood with glowing moss roots.',
    culturalRegion: 'Borneo',
    stabilityTrigger: 'low',
    cleansingItem: 'damar_resin',
    cleansingRewardArtifact: 'precursor_matrix',
    isMythic: true,
    isBoss: true,
    lore: 'Centuries-old ironwood giant that rises when loggers disrupt deep jungle sanctuaries.',
  },

  // --- MAJOR MYTHIC WORLD BOSS (1) ---
  hyang_batara_bhumi: {
    id: 'hyang_batara_bhumi',
    name: 'Hyang Batara Bhumi Primeval Titan',
    role: 'PREDATOR',
    biomes: ['volcanic', 'corrupted_barrens', 'mountain', 'crystal_spires'],
    activity: 'all_day',
    diet: 'AETHER_FEEDER',
    groupSize: [1, 1],
    fearRadius: 0,
    tameable: false,
    breedable: false,
    drops: [
      { itemId: 'pusaka_batara_bhumi_core', chance: 1.0, count: [1, 1] },
      { itemId: 'aether_crystal', chance: 1.0, count: [10, 20] },
      { itemId: 'gold_ingot', chance: 1.0, count: [6, 12] },
    ],
    rarity: 'aetheric',
    modelType: 'hyang_batara_bhumi',
    baseHealth: 1200,
    baseSpeed: 1.5,
    baseDamage: 45,
    description: 'Colossal Primordial Ley Titan forged from basalt, petrified Ulin, and glowing Aether crystals.',
    culturalRegion: 'Central Archipelago',
    stabilityTrigger: 'low',
    cleansingItem: 'pusaka_batara_bhumi',
    cleansingRewardArtifact: 'pusaka_batara_bhumi',
    isMythic: true,
    isBoss: true,
    lore: 'The primordial earth titan sleeping beneath Nusantara leylines. Awakens when stability decays to restore equilibrium through fire or cleansing rites.',
  },
};

