// Artifact & Ancient Knowledge Technology Progression Registry
// Unique passive relics with gameplay modifiers and recipe unlocks
import { ArtifactDef } from '../../types';

export const ARTIFACT_REGISTRY: Record<string, ArtifactDef> = {
  eye_of_aether: {
    id: 'eye_of_aether',
    name: 'Eye of the Aetherborn',
    rarity: 'epic',
    description: 'A luminous crystalline orb pulsing with arcane ley resonance.',
    lore: 'Carved by Precursor astromancers to gaze through physical strata and perceive concealed celestial leylines.',
    passiveAbility: 'Glows softly in total darkness and reveals nearby ore vein strata.',
    effectType: 'night_vision',
    unlockedRecipes: ['aether_lantern', 'leyline_compass'],
    iconColor: '#38bdf8',
  },
  chrono_core: {
    id: 'chrono_core',
    name: 'Perpetual Chrono Core',
    rarity: 'epic',
    description: 'An intricate clockwork gyroscopic heart powered by kinetic perpetual motion.',
    lore: 'Recovered from the lower cogworks of the Sunken Mechanum. It defies the normal dissipation of biological fatigue.',
    passiveAbility: 'Reduces sprint stamina drain by 50% and boosts movement agility.',
    effectType: 'stamina_boost',
    unlockedRecipes: ['kinetic_boots', 'recharging_talisman'],
    iconColor: '#fbbf24',
  },
  solaris_aegis: {
    id: 'solaris_aegis',
    name: 'Solaris Aegis Medallion',
    rarity: 'legendary',
    description: 'A heavy medallion forged from solar-fused ferrite and magma crystals.',
    lore: 'Worn by the Pyro-Wardens during the Great Sundering to brave molten magma rivers unharmed.',
    passiveAbility: 'Immunity to burning & fire damage; reflects hostile strikes as thermal flares.',
    effectType: 'thermal_aegis',
    unlockedRecipes: ['magma_furnace', 'pyroclast_blade'],
    iconColor: '#f97316',
  },
  tidal_pearl: {
    id: 'tidal_pearl',
    name: 'Pearl of the Abyssal Siren',
    rarity: 'epic',
    description: 'An iridescent bioluminescent sphere humming with oceanic tidal harmonics.',
    lore: 'Dredged from submerged precursor temples in the deep azure oceans. It allows effortless marine respiration.',
    passiveAbility: 'Provides continuous underwater oxygen and increases swimming propulsion.',
    effectType: 'water_breathing',
    unlockedRecipes: ['diver_mask', 'aquatic_spear'],
    iconColor: '#2dd4bf',
  },
  void_walker_ring: {
    id: 'void_walker_ring',
    name: 'Ring of the Void Sovereign',
    rarity: 'ancient',
    description: 'A pitch-black band wrought from folded dark matter and shimmering violet runes.',
    lore: 'The signet ring of the Shadow Sovereign. Nullifies eldritch spatial decay and protects against the Void.',
    passiveAbility: 'Grants immunity to Void corruption and unlocks Void Forge technology.',
    effectType: 'void_step',
    unlockedRecipes: ['void_greatsword', 'astral_plate_armor', 'dimensional_warp_anchor'],
    iconColor: '#c084fc',
  },
  precursor_matrix: {
    id: 'precursor_matrix',
    name: 'Precursor Knowledge Matrix',
    rarity: 'ancient',
    description: 'A floating polyhedral memory cube containing lost technological schematics.',
    lore: 'An intact archival library of the first builders, detailing atomic transmutation and celestial engineering.',
    passiveAbility: 'Unlocks Masterwork Smithing on Anvils and Advanced Mythril Recipes.',
    effectType: 'precursor_forge',
    unlockedRecipes: ['astral_pickaxe', 'astral_battleaxe', 'alchemical_infuser'],
    iconColor: '#ec4899',
  },
};
