// Artifact & Ancient Knowledge Technology Progression Registry
// Unique passive relics with gameplay modifiers and recipe unlocks
import { ArtifactDef } from '../../types';

export const ARTIFACT_REGISTRY: Record<string, ArtifactDef> = {
  eye_of_aether: {
    id: 'eye_of_aether',
    name: 'Eye of the Aetherborn',
    rarity: 'epic',
    description: 'A luminous crystalline orb pulsing with arcane ley resonance.',
    lore: 'Carved by Precursor astromancers to gaze through physical strata and perceive concealed celestial leylines.',
    passiveAbility: 'Glows softly in total darkness and reveals nearby ore vein strata.',
    effectType: 'night_vision',
    tags: ['arcane', 'vision', 'aether'],
    unlockedRecipes: ['aether_lantern', 'leyline_compass'],
    iconColor: '#38bdf8',
  },
  chrono_core: {
    id: 'chrono_core',
    name: 'Perpetual Chrono Core',
    rarity: 'epic',
    description: 'An intricate clockwork gyroscopic heart powered by kinetic perpetual motion.',
    lore: 'Recovered from the lower cogworks of the Sunken Mechanum. It defies the normal dissipation of biological fatigue.',
    passiveAbility: 'Reduces sprint stamina drain by 50% and boosts movement agility.',
    effectType: 'stamina_boost',
    tags: ['chrono', 'agility', 'kinetic'],
    unlockedRecipes: ['kinetic_boots', 'recharging_talisman'],
    iconColor: '#fbbf24',
  },
  solaris_aegis: {
    id: 'solaris_aegis',
    name: 'Solaris Aegis Medallion',
    rarity: 'legendary',
    description: 'A heavy medallion forged from solar-fused ferrite and magma crystals.',
    lore: 'Worn by the Pyro-Wardens during the Great Sundering to brave molten magma rivers unharmed.',
    passiveAbility: 'Immunity to burning & fire damage; reflects hostile strikes as thermal flares.',
    effectType: 'thermal_aegis',
    tags: ['thermal', 'defense', 'radiant'],
    unlockedRecipes: ['magma_furnace', 'pyroclast_blade'],
    iconColor: '#f97316',
  },
  tidal_pearl: {
    id: 'tidal_pearl',
    name: 'Pearl of the Abyssal Siren',
    rarity: 'epic',
    description: 'An iridescent bioluminescent sphere humming with oceanic tidal harmonics.',
    lore: 'Dredged from submerged precursor temples in the deep azure oceans. It allows effortless marine respiration.',
    passiveAbility: 'Provides continuous underwater oxygen and increases swimming propulsion.',
    effectType: 'water_breathing',
    tags: ['elemental', 'ocean', 'tide'],
    unlockedRecipes: ['diver_mask', 'aquatic_spear'],
    iconColor: '#2dd4bf',
  },
  void_walker_ring: {
    id: 'void_walker_ring',
    name: 'Ring of the Void Sovereign',
    rarity: 'ancient',
    description: 'A pitch-black band wrought from folded dark matter and shimmering violet runes.',
    lore: 'The signet ring of the Shadow Sovereign. Nullifies eldritch spatial decay and protects against the Void.',
    passiveAbility: 'Grants immunity to Void corruption and unlocks Void Forge technology.',
    effectType: 'void_step',
    tags: ['void', 'berserker', 'shadow'],
    unlockedRecipes: ['void_greatsword', 'astral_plate_armor', 'dimensional_warp_anchor'],
    iconColor: '#c084fc',
  },
  precursor_matrix: {
    id: 'precursor_matrix',
    name: 'Precursor Knowledge Matrix',
    rarity: 'ancient',
    description: 'A floating polyhedral memory cube containing lost technological schematics.',
    lore: 'An intact archival library of the first builders, detailing atomic transmutation and celestial engineering.',
    passiveAbility: 'Unlocks Masterwork Smithing on Anvils and Advanced Mythril Recipes.',
    effectType: 'precursor_forge',
    tags: ['precursor', 'arcane', 'knowledge'],
    unlockedRecipes: ['astral_pickaxe', 'astral_battleaxe', 'alchemical_infuser'],
    iconColor: '#ec4899',
  },
  solar_compass: {
    id: 'solar_compass',
    name: 'Solar Alignment Compass',
    rarity: 'rare',
    description: 'A golden astrolabe that tracks celestial leylines and ancient monolith nodes.',
    lore: 'Crafted to align expeditions with celestial solstice nodes across the continents.',
    passiveAbility: 'Points toward the closest undiscovered monolith and grants daylight agility.',
    effectType: 'stamina_boost',
    tags: ['vision', 'radiant', 'aether'],
    unlockedRecipes: ['leyline_compass'],
    iconColor: '#eab308',
  },
  berserker_fang: {
    id: 'berserker_fang',
    name: 'Fang of the Bloodbeast',
    rarity: 'epic',
    description: 'A serrated primordial fang infused with savage crimson adrenaline.',
    lore: 'Trophy of an ancient alpha dreadbeast slain in the deep abyssal chasms.',
    passiveAbility: 'Increases attack speed and melee damage when wounded.',
    effectType: 'stamina_boost',
    tags: ['berserker', 'shadow', 'combat'],
    unlockedRecipes: ['pyroclast_blade'],
    iconColor: '#ef4444',
  },
  heart_of_colossus: {
    id: 'heart_of_colossus',
    name: 'Heart of the Stone Colossus',
    rarity: 'legendary',
    description: 'A petrified geo-crystalline core humming with gravitational density.',
    lore: 'Core of the ancient guardians that once secured the deep world vaults.',
    passiveAbility: 'Massively increases maximum poise and staggers attacking foes on parry.',
    effectType: 'thermal_aegis',
    tags: ['defense', 'colossus', 'earth'],
    unlockedRecipes: ['astral_plate_armor'],
    iconColor: '#64748b',
  },
};
