// Artifact & Ancient Knowledge Technology Progression Registry
// Unique passive relics with gameplay modifiers and recipe unlocks
import { ArtifactDef } from '../../types';

export const ARTIFACT_REGISTRY: Record<string, ArtifactDef> = {
  eye_of_aether: {
    id: 'eye_of_aether',
    name: 'Eye of the Aetherborn',
    rarity: 'epic',
    description: 'A luminous crystalline orb pulsing with arcane ley resonance.',
    lore: 'Carved by Precursor astromancers to gaze through physical strata and perceive concealed celestial leylines.',
    passiveAbility: 'Glows softly in total darkness and reveals nearby ore vein strata.',
    effectType: 'night_vision',
    tags: ['arcane', 'vision', 'aether'],
    unlockedRecipes: ['aether_lantern', 'leyline_compass'],
    iconColor: '#38bdf8',
  },
  chrono_core: {
    id: 'chrono_core',
    name: 'Perpetual Chrono Core',
    rarity: 'epic',
    description: 'An intricate clockwork gyroscopic heart powered by kinetic perpetual motion.',
    lore: 'Recovered from the lower cogworks of the Sunken Mechanum. It defies the normal dissipation of biological fatigue.',
    passiveAbility: 'Reduces sprint stamina drain by 50% and boosts movement agility.',
    effectType: 'stamina_boost',
    tags: ['chrono', 'agility', 'kinetic'],
    unlockedRecipes: ['kinetic_boots', 'recharging_talisman'],
    iconColor: '#fbbf24',
  },
  solaris_aegis: {
    id: 'solaris_aegis',
    name: 'Solaris Aegis Medallion',
    rarity: 'legendary',
    description: 'A heavy medallion forged from solar-fused ferrite and magma crystals.',
    lore: 'Worn by the Pyro-Wardens during the Great Sundering to brave molten magma rivers unharmed.',
    passiveAbility: 'Immunity to burning & fire damage; reflects hostile strikes as thermal flares.',
    effectType: 'thermal_aegis',
    tags: ['thermal', 'defense', 'radiant'],
    unlockedRecipes: ['magma_furnace', 'pyroclast_blade'],
    iconColor: '#f97316',
  },
  tidal_pearl: {
    id: 'tidal_pearl',
    name: 'Pearl of the Abyssal Siren',
    rarity: 'epic',
    description: 'An iridescent bioluminescent sphere humming with oceanic tidal harmonics.',
    lore: 'Dredged from submerged precursor temples in the deep azure oceans. It allows effortless marine respiration.',
    passiveAbility: 'Provides continuous underwater oxygen and increases swimming propulsion.',
    effectType: 'water_breathing',
    tags: ['elemental', 'ocean', 'tide'],
    unlockedRecipes: ['diver_mask', 'aquatic_spear'],
    iconColor: '#2dd4bf',
  },
  void_walker_ring: {
    id: 'void_walker_ring',
    name: 'Ring of the Void Sovereign',
    rarity: 'ancient',
    description: 'A pitch-black band wrought from folded dark matter and shimmering violet runes.',
    lore: 'The signet ring of the Shadow Sovereign. Nullifies eldritch spatial decay and protects against the Void.',
    passiveAbility: 'Grants immunity to Void corruption and unlocks Void Forge technology.',
    effectType: 'void_step',
    tags: ['void', 'berserker', 'shadow'],
    unlockedRecipes: ['void_greatsword', 'astral_plate_armor', 'dimensional_warp_anchor'],
    iconColor: '#c084fc',
  },
  precursor_matrix: {
    id: 'precursor_matrix',
    name: 'Precursor Knowledge Matrix',
    rarity: 'ancient',
    description: 'A floating polyhedral memory cube containing lost technological schematics.',
    lore: 'An intact archival library of the first builders, detailing atomic transmutation and celestial engineering.',
    passiveAbility: 'Unlocks Masterwork Smithing on Anvils and Advanced Mythril Recipes.',
    effectType: 'precursor_forge',
    tags: ['precursor', 'arcane', 'knowledge'],
    unlockedRecipes: ['astral_pickaxe', 'astral_battleaxe', 'alchemical_infuser'],
    iconColor: '#ec4899',
  },
  solar_compass: {
    id: 'solar_compass',
    name: 'Solar Alignment Compass',
    rarity: 'rare',
    description: 'A golden astrolabe that tracks celestial leylines and ancient monolith nodes.',
    lore: 'Crafted to align expeditions with celestial solstice nodes across the continents.',
    passiveAbility: 'Points toward the closest undiscovered monolith and grants daylight agility.',
    effectType: 'stamina_boost',
    tags: ['vision', 'radiant', 'aether'],
    unlockedRecipes: ['leyline_compass'],
    iconColor: '#eab308',
  },
  berserker_fang: {
    id: 'berserker_fang',
    name: 'Fang of the Bloodbeast',
    rarity: 'epic',
    description: 'A serrated primordial fang infused with savage crimson adrenaline.',
    lore: 'Trophy of an ancient alpha dreadbeast slain in the deep abyssal chasms.',
    passiveAbility: 'Increases attack speed and melee damage when wounded.',
    effectType: 'stamina_boost',
    tags: ['berserker', 'shadow', 'combat'],
    unlockedRecipes: ['pyroclast_blade'],
    iconColor: '#ef4444',
  },
  heart_of_colossus: {
    id: 'heart_of_colossus',
    name: 'Heart of the Stone Colossus',
    rarity: 'legendary',
    description: 'A petrified geo-crystalline core humming with gravitational density.',
    lore: 'Core of the ancient guardians that once secured the deep world vaults.',
    passiveAbility: 'Massively increases maximum poise and staggers attacking foes on parry.',
    effectType: 'thermal_aegis',
    tags: ['defense', 'colossus', 'earth'],
    unlockedRecipes: ['astral_plate_armor'],
    iconColor: '#64748b',
  },

  // --- NUSANTARA CULTURAL ARTIFACT FAMILIES ---
  // 1. IRRIGATION FAMILY
  mustika_tirta_subak: {
    id: 'mustika_tirta_subak',
    name: 'Mustika Tirta Subak Wilwatikta',
    rarity: 'legendary',
    description: 'Batu mustika air jernih berkilau cyan yang memancarkan getaran berkah kesuburan bumi.',
    lore: 'Ditemukan di hulu mata air keramat Gunung Lawu oleh para sesepuh Majapahit kuno.',
    passiveAbility: '+40% Kecepatan Panen Padi, retensi air otomatis, dan nafas dalam air.',
    effectType: 'water_breathing',
    tags: ['irrigation', 'tirta', 'harvest', 'jawa'],
    unlockedRecipes: ['subak_irrigation_gate', 'sacred_subak_aqueduct'],
    iconColor: '#38bdf8',
  },
  kendi_amerta_wilwatikta: {
    id: 'kendi_amerta_wilwatikta',
    name: 'Kendi Amerta Kerajaan Majapahit',
    rarity: 'epic',
    description: 'Kendi tembaga berukir teratai berisi tetesan embun abadi yang memulihkan vitalitas.',
    lore: 'Pusaka istana untuk upacara ruwat bumi dan pembersihan kutukan tanah.',
    passiveAbility: 'Regenerasi HP pasif saat berdiri di dekat air atau persawahan berundak.',
    effectType: 'stamina_boost',
    tags: ['irrigation', 'elemental', 'tirta', 'jawa'],
    unlockedRecipes: ['subak_irrigation_gate'],
    iconColor: '#0ea5e9',
  },
  gading_air_subak: {
    id: 'gading_air_subak',
    name: 'Gading Tirta Amerta Dewata',
    rarity: 'epic',
    description: 'Pusaka gading putih bertakik kristal ley pembelah arus air suci Pura Besakih.',
    lore: 'Membimbing aliran air dari danau kawah Batur melintasi lembah sawah bertingkat.',
    passiveAbility: 'Menggandakan perolehan Beras Suci Tirta dan menyuburkan tanaman sekitar.',
    effectType: 'stamina_boost',
    tags: ['irrigation', 'tirta', 'bali'],
    unlockedRecipes: ['sacred_subak_aqueduct'],
    iconColor: '#7dd3fc',
  },

  // 2. NAVIGATION FAMILY
  kompas_kristal_samudra: {
    id: 'kompas_kristal_samudra',
    name: 'Kompas Kristal Samudra Banda',
    rarity: 'legendary',
    description: 'Astrolabe karang dan kuningan berjarum kristal biru yang menunjuk ke pusaran leylines terdekat.',
    lore: 'Dipakai para nahkoda kapal pinisi menyeberangi lautan badai kepulauan rempah.',
    passiveAbility: 'Membelah kabut navigasi samudra dan memberi +35% kecepatan perahu layar.',
    effectType: 'night_vision',
    tags: ['navigation', 'ocean', 'vision', 'nusa'],
    unlockedRecipes: ['coral_navigation_beacon'],
    iconColor: '#0284c7',
  },
  suar_rimba_borneo: {
    id: 'suar_rimba_borneo',
    name: 'Suar Rimba Ulin Purba',
    rarity: 'epic',
    description: 'Lentera kayu ulin berisi getah damar zamrud yang tak pernah padam oleh air sungai deras.',
    lore: 'Panduan suku Dayak menyusuri riak Batang Kapuas di tengah gelapnya hutan hujan purba.',
    passiveAbility: 'Kebal terhadap arus deras sungai dan memancarkan pendaran hijau pelindung.',
    effectType: 'night_vision',
    tags: ['navigation', 'nature', 'vision', 'borneo'],
    unlockedRecipes: ['river_navigation_beacon'],
    iconColor: '#10b981',
  },
  noken_arah_angin: {
    id: 'noken_arah_angin',
    name: 'Noken Penuntun Angin Baliem',
    rarity: 'epic',
    description: 'Tas rajutan serat anggrek hutan yang bergetar lembut saat mendekati situs keramat kuno.',
    lore: 'Ditenun oleh tetua Lembah Baliem untuk memandu pemburu menembus badai salju Jayawijaya.',
    passiveAbility: 'Mengurangi stamina lari sebesar 35% dan menunjukkan lokasi pilar monolit tersembunyi.',
    effectType: 'stamina_boost',
    tags: ['navigation', 'agility', 'papua'],
    unlockedRecipes: ['honai_hearth_core'],
    iconColor: '#c084fc',
  },

  // 3. GUARDIAN FAMILY
  patung_candi_bentar: {
    id: 'patung_candi_bentar',
    name: 'Patung Candi Bentar Purba',
    rarity: 'legendary',
    description: 'Arca batu paras berukir wajah Barong penjaga batas suci dari marabahaya kegelapan.',
    lore: 'Memisahkan dunia luar dari pelataran suci dengan getaran medan energi penangkal void.',
    passiveAbility: 'Menciptakan aura pemurni yang memperlambat monster kegelapan sebesar 40%.',
    effectType: 'thermal_aegis',
    tags: ['guardian', 'defense', 'bali'],
    unlockedRecipes: ['candi_bentar_aether_gate'],
    iconColor: '#38bdf8',
  },
  perisai_asmat_pusaka: {
    id: 'perisai_asmat_pusaka',
    name: 'Perisai Asmat Berukir Pusaka',
    rarity: 'legendary',
    description: 'Perisai kayu besi berukir motif Mbis leluhur yang menyerap hentakan fisik terberat.',
    lore: 'Diwariskan turun-temurun oleh para kesatria Asmat untuk melindungi honai dari serangan buas.',
    passiveAbility: 'Mementalkan serangan musuh saat parry dan memberikan kekebalan knockback.',
    effectType: 'thermal_aegis',
    tags: ['guardian', 'defense', 'earth', 'papua'],
    unlockedRecipes: ['asmat_canopy_sentinel'],
    iconColor: '#a855f7',
  },
  tanduk_pa_tedong: {
    id: 'tanduk_pa_tedong',
    name: 'Tanduk Pa\'tedong Pusaka Toraja',
    rarity: 'epic',
    description: 'Pasang tanduk kerbau belang bonga yang diukir dengan simbol matahari Pa\'barre Allo.',
    lore: 'Dipasang di tiang utama Tongkonan sebagai lambang keberanian dan perlindungan leluhur.',
    passiveAbility: '+50% Poise ketahanan fisik dan melipatgandakan daya pukul senjata gada.',
    effectType: 'thermal_aegis',
    tags: ['guardian', 'colossus', 'toraja'],
    unlockedRecipes: ['simbuang_standing_stone'],
    iconColor: '#eab308',
  },

  // 4. STORM FAMILY
  penangkal_badai_ternate: {
    id: 'penangkal_badai_ternate',
    name: 'Penangkal Badai Ternate',
    rarity: 'legendary',
    description: 'Pusaka tembaga kuningan berujung kristal yang menyerap kilatan petir samudra.',
    lore: 'Ditempa oleh empu Ternate untuk mengalirkan energi badai laut ke benteng pertahanan.',
    passiveAbility: 'Menyerap 100% kerusakan petir dan mengubahnya menjadi ledakan listrik balasan.',
    effectType: 'thermal_aegis',
    tags: ['storm', 'thermal', 'aether', 'nusa'],
    unlockedRecipes: ['storm_lightning_collector'],
    iconColor: '#38bdf8',
  },
  batu_guntur_marapi: {
    id: 'batu_guntur_marapi',
    name: 'Batu Guntur Marapi',
    rarity: 'epic',
    description: 'Bongkahan batu vulkanik hitam bermuatan statis tinggi yang memercikkan bunga api ungu.',
    lore: 'Jatuh dari puncak Marapi saat terjadi letusan leylines dahsyat ribuan tahun silam.',
    passiveAbility: 'Serangan berat melepaskan gelombang kejut petir yang menyengat musuh sekitar.',
    effectType: 'void_step',
    tags: ['storm', 'thermal', 'arcane', 'minang'],
    unlockedRecipes: ['marapi_resonance_spire'],
    iconColor: '#f59e0b',
  },
  keris_kilat_singasari: {
    id: 'keris_kilat_singasari',
    name: 'Keris Pamor Kilat Singasari',
    rarity: 'legendary',
    description: 'Bilah keris berkelok sembilan berpamor meteorit yang mendesis saat terhunus.',
    lore: 'Ditempa dari paduan logam langit dan leylines Merapi untuk para senapati perang.',
    passiveAbility: '+25% Kecepatan Serangan dan +20% Peluang Serangan Kritis berelemen kilat.',
    effectType: 'stamina_boost',
    tags: ['storm', 'combat', 'berserker', 'jawa'],
    unlockedRecipes: ['candi_resonance_stupa'],
    iconColor: '#fbbf24',
  },

  // 5. HARVEST FAMILY
  ani_ani_emas_sri: {
    id: 'ani_ani_emas_sri',
    name: 'Ani-Ani Emas Dewi Sri',
    rarity: 'legendary',
    description: 'Pisau ketam tradisional bertatah emas murni penghormatan bagi sang dewi padi.',
    lore: 'Digunakan saat panen raya pertama di dataran Wilwatikta untuk memetik bulir padi suci.',
    passiveAbility: 'Setiap panen berpeluang 35% memberikan panen ganda dan Kristal Aether ekstra.',
    effectType: 'stamina_boost',
    tags: ['harvest', 'nature', 'jawa'],
    unlockedRecipes: ['subak_irrigation_gate'],
    iconColor: '#facc15',
  },
  lumbung_alang_pusaka: {
    id: 'lumbung_alang_pusaka',
    name: 'Lumbung Alang Pa\'ssura Toraja',
    rarity: 'epic',
    description: 'Relik miniatur lumbung Alang berukir yang memancarkan aura pengawetan hasil bumi abadi.',
    lore: 'Disimpan di bawah atap Tongkonan untuk menjaga kemakmuran keluarga selama musim paceklik.',
    passiveAbility: 'Melipatgandakan daya simpan bahan makanan dan mencegah penurunan kesegaran.',
    effectType: 'stamina_boost',
    tags: ['harvest', 'earth', 'toraja'],
    unlockedRecipes: ['alang_resonance_vault'],
    iconColor: '#ca8a04',
  },
  bakul_beras_rojolele: {
    id: 'bakul_beras_rojolele',
    name: 'Bakul Beras Wilwatikta',
    rarity: 'epic',
    description: 'Bakul anyaman bambu petung beraroma pandan wangi yang tak pernah kehabisan bulir beras.',
    lore: 'Pemberian para tetua desa kepada musafir yang menempuh jalan kebajikan.',
    passiveAbility: 'Memulihkan cadangan makanan saat beristirahat di dekat pemukiman Nusantara.',
    effectType: 'stamina_boost',
    tags: ['harvest', 'tirta', 'minang'],
    unlockedRecipes: ['rangkiang_aether_lantern'],
    iconColor: '#eab308',
  },
};
